"""Generate the Supply-Chain page mock (Tier-0) from REAL sector co-movement data.

Tier 0 per supply_chain_page.md: we have nodes (company_profiles.sector) and ZERO
edges. This renders the chord format the design settles on, fed by a sector x sector
252d return-correlation matrix computed from price_data.

🛑 THIS IS CO-MOVEMENT, NOT DEPENDENCY. A correlation is not a supply relationship.
The mock exists to lock the visual format and answer the platform question (chord +
hover-dimming is the Streamlit stress case) — it is NOT the product. The real page
waits on a `supply_chain_edges` table (Tier 1 EDGAR extraction or Tier 2 vendor feed),
a decision deliberately left to the user.

Numbers here are REAL (unlike the raw spec's invented "514 companies / 649 edges /
$68.4T") — the house lesson from macro_page_mock.html, whose "10/10 indicators" were
fabricated while the real board could fill 2.

Usage:
    python scripts/build_supply_chain_mock.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import src.db as db  # noqa: E402

DB_PATH = ROOT / "data" / "market_data.duckdb"
OUT = (ROOT / "docs" / "session_logs" / "sprint_14" / "plans" / "dashboard_uplift"
       / "supply_chain_mock.html")
WINDOW = 252  # trading days

# theta palette (style.md) — one hue per sector, stable ordering.
SECTOR_COLORS = {
    "Technology": "#6b6a3a", "Financial Services": "#a5542f",
    "Healthcare": "#3f7d4e", "Industrials": "#b9862e",
    "Consumer Cyclical": "#7a6a9a", "Consumer Defensive": "#4a7a8a",
    "Energy": "#8a5a3a", "Communication Services": "#9a6a7a",
    "Basic Materials": "#5a7a5a", "Real Estate": "#8a7a4a",
    "Utilities": "#6a7a8a",
}


def load_matrix() -> tuple[pd.DataFrame, pd.Series, int]:
    """252d sector-return correlation + per-sector company counts.

    Equal-weight daily sector return from price_data; ETF pseudo-sectors excluded
    (company_profiles tags 16 ETF:* buckets that aren't real sectors)."""
    con = db.connect(str(DB_PATH), read_only=True)
    try:
        rets = con.execute("""
            WITH universe AS (
                SELECT ticker, sector FROM company_profiles
                WHERE sector IS NOT NULL AND sector NOT LIKE 'ETF:%'
            ),
            px AS (
                SELECT p.date, u.sector, p.close,
                       LAG(p.close) OVER (PARTITION BY p.ticker ORDER BY p.date) prev
                FROM price_data p JOIN universe u USING (ticker)
                WHERE p.date >= (SELECT MAX(date) - INTERVAL 400 DAY FROM price_data)
            )
            SELECT date, sector, AVG(close / prev - 1) AS ret
            FROM px WHERE prev IS NOT NULL AND prev > 0
            GROUP BY date, sector
        """).fetchdf()
        counts = con.execute("""
            SELECT sector, COUNT(*) n FROM company_profiles
            WHERE sector IS NOT NULL AND sector NOT LIKE 'ETF:%'
            GROUP BY sector
        """).fetchdf().set_index("sector")["n"]
    finally:
        con.close()

    wide = rets.pivot(index="date", columns="sector", values="ret")
    wide = wide.dropna(how="any").tail(WINDOW)
    return wide.corr(), counts, len(wide)


def to_chord_matrix(corr: pd.DataFrame) -> tuple[list[str], list[list[float]]]:
    """Chord needs a non-negative weight matrix with a zero diagonal.

    Self-correlation (the 1.0 diagonal) would swamp every ribbon, and a negative
    correlation has no chord representation — clipped at 0 and captioned.
    """
    order = sorted(corr.columns, key=lambda s: -corr[s].drop(s).mean())
    m = corr.loc[order, order].clip(lower=0.0)
    for s in order:
        m.loc[s, s] = 0.0
    return order, m.round(4).values.tolist()


def build_html(order: list[str], matrix: list[list[float]],
               counts: pd.Series, n_days: int, as_of: str) -> str:
    sectors = [{"id": s, "label": s, "companies": int(counts.get(s, 0)),
                "color": SECTOR_COLORS.get(s, "#8a8272")} for s in order]
    n_co = sum(s["companies"] for s in sectors)
    payload = json.dumps({"sectors": sectors, "matrix": matrix}, separators=(",", ":"))

    return f"""<!-- Supply-Chain page — standalone Tier-0 mock. REAL co-movement data,
     NOT supply-chain edges (we have zero). Generated by scripts/build_supply_chain_mock.py.
     Purpose: lock the chord format + answer the platform question. Open directly. -->
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Supply Chain — Tier-0 mock</title>
<script src="https://d3js.org/d3.v7.min.js"></script>
<style>
  :root{{
    --background:#fcfbf8; --foreground:#1c1a17; --muted:#8a8272;
    --border:#e8e3d6; --accent:#6b6a3a; --rust:#a5542f; --warn:#b9862e;
    --card:#fffefb; --ring:#6b6a3a;
  }}
  *{{box-sizing:border-box}}
  body{{margin:0;background:var(--background);color:var(--foreground);
    font-family:"Source Serif 4",Georgia,serif;font-size:15px;line-height:1.5}}
  .mono{{font-family:"JetBrains Mono",ui-monospace,Menlo,monospace;
    font-variant-numeric:tabular-nums}}
  .wrap{{max-width:1180px;margin:0 auto;padding:28px 24px 80px}}
  .hero{{text-align:center;margin:34px 0 6px}}
  .hero h1{{font-size:34px;font-weight:600;margin:0;letter-spacing:-.01em}}
  .hero .sub{{color:var(--muted);font-size:17px;font-style:italic;margin-top:4px}}
  .caveat{{max-width:760px;margin:18px auto 0;padding:12px 16px;
    background:#fdf6e8;border:1px solid var(--warn);border-radius:4px;
    font-size:13px;line-height:1.55}}
  .caveat b{{color:#8a6420}}
  .pills{{display:flex;gap:8px;justify-content:center;flex-wrap:wrap;margin:26px 0 6px}}
  .pill{{font-family:"JetBrains Mono",monospace;font-size:11px;letter-spacing:.08em;
    text-transform:uppercase;padding:5px 12px;border:1px solid var(--border);
    border-radius:999px;color:var(--muted);background:var(--card);cursor:not-allowed}}
  .pill.dim{{opacity:.55}}
  .meta{{text-align:center;color:var(--muted);font-size:12px;margin-top:10px}}
  #chart{{display:block;margin:0 auto}}
  .grid-bg{{background-image:linear-gradient(var(--border) 1px,transparent 1px),
    linear-gradient(90deg,var(--border) 1px,transparent 1px);
    background-size:60px 60px;background-position:center;opacity:.5;
    position:absolute;inset:0;z-index:0;pointer-events:none}}
  .chartwrap{{position:relative;margin-top:8px}}
  .arc-label{{font-family:"JetBrains Mono",monospace;font-size:10px;fill:var(--foreground)}}
  .arc-sub{{font-family:"JetBrains Mono",monospace;font-size:9px;fill:var(--muted)}}
  #tip{{position:fixed;pointer-events:none;opacity:0;background:var(--card);
    border:1px solid var(--border);border-radius:4px;padding:8px 10px;font-size:12px;
    box-shadow:0 2px 10px rgba(0,0,0,.08);transition:opacity 120ms;z-index:10}}
  .hint{{text-align:center;color:var(--muted);font-size:12px;font-style:italic;margin-top:14px}}
  footer{{margin-top:40px;padding-top:16px;border-top:1px solid var(--border);
    color:var(--muted);font-size:12px}}
  @media(max-width:820px){{
    #chart{{display:none}} .mobile{{display:block!important}}
  }}
  .mobile{{display:none;text-align:center;padding:40px 20px;color:var(--muted)}}
</style>
</head>
<body>
<div class="wrap">

  <div class="hero">
    <h1>The market is not a list of sectors.</h1>
    <div class="sub">It is a dependency system.</div>
  </div>

  <div class="caveat">
    <b>⚠ Tier-0 mock — this is CO-MOVEMENT, not dependency.</b><br>
    Ribbons are {WINDOW}-day return <i>correlation</i> between equal-weight sector
    indices ({n_days} trading days to {as_of}), computed from <span class="mono">price_data</span>.
    <b>A correlation is not a supply relationship.</b> Two sectors move together for
    many reasons — shared macro factors, common ownership, index flows — none of which
    imply one supplies the other. The real page needs a
    <span class="mono">supply_chain_edges</span> table extracted from 10-K disclosures
    (Tier 1) or bought from a vendor (Tier 2); <b>we currently have zero edges</b>.
    This exists to lock the visual format, not to be read as a dependency map.
  </div>

  <div class="pills">
    <span class="pill dim">HBM</span><span class="pill dim">DDR</span>
    <span class="pill dim">NAND</span><span class="pill dim">Storage</span>
    <span class="pill dim">Packaging</span><span class="pill dim">AI Compute</span>
    <span class="pill dim">AI Net</span><span class="pill dim">Power</span>
  </div>
  <div class="meta mono">sub-chain lanes not yet authored — hand-curated map, independent of edges</div>

  <div class="chartwrap">
    <div class="grid-bg"></div>
    <svg id="chart" width="760" height="760" viewBox="0 0 760 760"></svg>
    <div class="mobile">Best viewed on desktop.<br><br>The chord diagram needs width to be legible.</div>
  </div>

  <div class="meta mono" id="metaline"></div>
  <div class="hint">Hover a sector arc to isolate its ribbons — try Industrials (the hub).</div>

  <footer>
    <b>What would make this real:</b> a directional, weighted
    <span class="mono">supply_chain_edges(src_ticker, dst_ticker, weight, direction,
    source_type, as_of, confidence)</span> table. Tier 1 = EDGAR 10-K "significant
    customers" extraction (Reg S-K Item 101 mandates disclosing customers ≥10% of
    revenue) — real and high-signal but a multi-week engine, not a dashboard change.
    Tier 2 = vendor feed (FactSet Revere / Bloomberg SPLC), paid, collapses weeks into
    an import. <b>Build-vs-buy is an open user decision.</b>
    <br><br>
    Generated by <span class="mono">scripts/build_supply_chain_mock.py</span> —
    re-run to refresh. Design: <span class="mono">supply_chain_page.md</span>.
  </footer>
</div>
<div id="tip"></div>

<script>
// d3 is loaded from CDN (unlike macro_page_mock.html, which is fully self-contained).
// Fail loudly rather than rendering a blank page offline.
if (typeof d3 === "undefined") {{
  document.getElementById("chart").outerHTML =
    '<div style="text-align:center;padding:60px 20px;color:#b23b3b">' +
    '<b>d3 failed to load</b><br><span style="color:#8a8272;font-size:13px">' +
    'This mock fetches d3 v7 from a CDN — you are offline, or the CDN is blocked.<br>' +
    'The data below is unaffected; only the chord render needs d3.</span></div>';
}}
const DATA = {payload};
const sectors = DATA.sectors, matrix = DATA.matrix;
document.getElementById("metaline").textContent =
  `{n_co} companies · {len(order)} sectors · {WINDOW}d correlation · 0 supply-chain edges`;

if (typeof d3 !== "undefined") {{
const W = 760, H = 760, outerR = Math.min(W,H)*0.5 - 110;
const innerR = outerR - 20;

const svg = d3.select("#chart");
const g = svg.append("g").attr("transform", `translate(${{W/2}},${{H/2}})`);

const chord = d3.chord().padAngle(0.02).sortSubgroups(d3.descending)(matrix);
const arc = d3.arc().innerRadius(innerR).outerRadius(outerR);
const ribbon = d3.ribbon().radius(innerR - 2);
const tip = d3.select("#tip");

function showTip(html, ev){{
  tip.html(html).style("opacity",1)
     .style("left",(ev.clientX+14)+"px").style("top",(ev.clientY+14)+"px");
}}
function hideTip(){{ tip.style("opacity",0); }}

// Ribbons
const ribbons = g.append("g").selectAll("path").data(chord).join("path")
  .attr("d", ribbon)
  .attr("fill", d => sectors[d.source.index].color)
  .attr("fill-opacity", 0.35)
  .attr("stroke", "rgba(0,0,0,.06)")
  .style("transition","opacity 180ms")
  .on("mouseenter", (ev,d) => {{
    ribbons.attr("fill-opacity", x => x===d ? 0.85 : 0.06);
    arcs.attr("fill-opacity", x =>
      (x.index===d.source.index || x.index===d.target.index) ? 1 : 0.35);
    const a = sectors[d.source.index].label, b = sectors[d.target.index].label;
    showTip(`<b>${{a}} ↔ ${{b}}</b><br><span class="mono">corr ${{d.source.value.toFixed(2)}}</span>
             <br><span style="color:#8a8272">co-movement, not dependency</span>`, ev);
  }})
  .on("mousemove", (ev) => tip.style("left",(ev.clientX+14)+"px").style("top",(ev.clientY+14)+"px"))
  .on("mouseleave", () => {{
    ribbons.attr("fill-opacity", 0.35); arcs.attr("fill-opacity", 1); hideTip();
  }});

// Sector arcs
const arcs = g.append("g").selectAll("path").data(chord.groups).join("path")
  .attr("d", arc)
  .attr("fill", d => sectors[d.index].color)
  .attr("tabindex", 0)
  .style("cursor","pointer")
  .style("transition","opacity 180ms")
  .on("mouseenter", (ev,d) => {{
    ribbons.attr("fill-opacity", x =>
      (x.source.index===d.index || x.target.index===d.index) ? 0.85 : 0.06);
    arcs.attr("fill-opacity", x => x.index===d.index ? 1 : 0.35);
    const s = sectors[d.index];
    showTip(`<b>${{s.label}}</b><br><span class="mono">${{s.companies}} companies</span>
             <br><span class="mono">Σ corr ${{d.value.toFixed(2)}}</span>`, ev);
  }})
  .on("mousemove", (ev) => tip.style("left",(ev.clientX+14)+"px").style("top",(ev.clientY+14)+"px"))
  .on("mouseleave", () => {{
    ribbons.attr("fill-opacity", 0.35); arcs.attr("fill-opacity", 1); hideTip();
  }});

// Arc labels, flipped past π
g.append("g").selectAll("g").data(chord.groups).join("g")
  .attr("transform", d => {{
    const a = (d.startAngle + d.endAngle)/2;
    return `rotate(${{a*180/Math.PI - 90}}) translate(${{outerR + 8}},0)`
         + (a > Math.PI ? " rotate(180)" : "");
  }})
  .call(gg => {{
    gg.append("text").attr("class","arc-label")
      .attr("text-anchor", d => ((d.startAngle+d.endAngle)/2 > Math.PI) ? "end" : "start")
      .attr("dy","-0.1em")
      .text(d => sectors[d.index].label);
    gg.append("text").attr("class","arc-sub")
      .attr("text-anchor", d => ((d.startAngle+d.endAngle)/2 > Math.PI) ? "end" : "start")
      .attr("dy","1.05em")
      .text(d => sectors[d.index].companies + " cos");
  }});
}}  // end d3 guard
</script>
</body>
</html>
"""


def main() -> int:
    corr, counts, n_days = load_matrix()
    order, matrix = to_chord_matrix(corr)
    as_of = pd.Timestamp.now().strftime("%Y-%m-%d")

    print(f"[OK] {len(order)} sectors, {n_days} trading days")
    print(corr.loc[order, order].round(2).to_string())
    off_diag = [v for i, row in enumerate(matrix) for j, v in enumerate(row) if i != j]
    print(f"\ncorr range (off-diagonal, clipped at 0): "
          f"{min(off_diag):.2f} .. {max(off_diag):.2f}")

    OUT.write_text(build_html(order, matrix, counts, n_days, as_of), encoding="utf-8")
    print(f"\n[OK] wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size/1024:.0f} KB)")
    print("     [WARN] co-movement, NOT dependency - caveat rendered on the page.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
