"""Seed feature_catalog and model_feature_sets for M01_baseline v0.1.

Reads metrics from models/m01_baseline/v1/metadata.json — nothing hardcoded.
Safe to run multiple times (INSERT OR IGNORE).

Usage:
    python scripts/populate_feature_catalog.py [--db PATH]
"""

import json
import sys
from pathlib import Path

import duckdb

sys.path.append(str(Path(__file__).parent.parent))
from src.model_registry import ModelRegistry

DB_PATH = Path(__file__).parent.parent / "data" / "market_data.duckdb"
METADATA_PATH = Path(__file__).parent.parent / "models" / "m01_baseline" / "v1" / "metadata.json"

VERSION_INTRODUCED = "v3.1"
VERSION_RETIRED_LOG = "v3.2"   # log_ features retired when v3.2 removes them from the view
FEATURE_SET_ID = "fs_m01_baseline_v0.1"
MODEL_VERSION_ID = "M01_baseline_v0.1"

# ------------------------------------------------------------------
# Feature definitions: all 106 features declared in FEATURE_GROUPS
# (105 valid + atr_delta which was declared but missing from artifact)
# ------------------------------------------------------------------
FEATURE_DEFS = [
    # ---- Moving_Averages ----
    {
        "feature_name": "close_above_sma200",
        "feature_group": "Moving_Averages",
        "description": "Binary flag: close > SMA(200)",
        "formula_summary": "1 if close > SMA(200) else 0",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "BOOLEAN",
        "is_categorical": False,
    },
    {
        "feature_name": "price_vs_sma_50",
        "feature_group": "Moving_Averages",
        "description": "Price distance from SMA(50) as percentage",
        "formula_summary": "(close / SMA(50) - 1) * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "price_vs_sma_150",
        "feature_group": "Moving_Averages",
        "description": "Price distance from SMA(150) as percentage",
        "formula_summary": "(close / SMA(150) - 1) * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "price_vs_sma_200",
        "feature_group": "Moving_Averages",
        "description": "Price distance from SMA(200) as percentage",
        "formula_summary": "(close / SMA(200) - 1) * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "sma_50_slope",
        "feature_group": "Moving_Averages",
        "description": "Slope of SMA(50) over past 5 bars as percentage",
        "formula_summary": "(SMA50_today / SMA50_5d_ago - 1) * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "price_vs_sma_50_delta",
        "feature_group": "Moving_Averages",
        "description": "1-day percentage change of price_vs_sma_50",
        "formula_summary": "(price_vs_sma_50 - lag(price_vs_sma_50, 1)) / abs(lag(price_vs_sma_50, 1)) * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "price_vs_sma_150_delta",
        "feature_group": "Moving_Averages",
        "description": "1-day percentage change of price_vs_sma_150",
        "formula_summary": "(price_vs_sma_150 - lag(price_vs_sma_150, 1)) / abs(lag(price_vs_sma_150, 1)) * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "price_vs_sma_200_delta",
        "feature_group": "Moving_Averages",
        "description": "1-day percentage change of price_vs_sma_200",
        "formula_summary": "(price_vs_sma_200 - lag(price_vs_sma_200, 1)) / abs(lag(price_vs_sma_200, 1)) * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    # ---- Momentum_RS ----
    {
        "feature_name": "rs_line_uptrend",
        "feature_group": "Momentum_RS",
        "description": "Binary flag: RS line is above its 50-day MA",
        "formula_summary": "1 if rs_line > SMA(rs_line, 50) else 0",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "BOOLEAN",
        "is_categorical": False,
    },
    {
        "feature_name": "rs_line_delta",
        "feature_group": "Momentum_RS",
        "description": "1-day percentage change of RS line",
        "formula_summary": "(rs_line - lag(rs_line, 1)) / abs(lag(rs_line, 1)) * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "rs_line_lag_delta",
        "feature_group": "Momentum_RS",
        "description": "2-to-1 day percentage change of RS line (lagged delta)",
        "formula_summary": "(lag(rs_line, 1) - lag(rs_line, 2)) / abs(lag(rs_line, 2)) * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "rs_rating",
        "feature_group": "Momentum_RS",
        "description": "IBD-style RS rating: percentile rank of momentum score vs universe",
        "formula_summary": "PERCENT_RANK() OVER (ORDER BY rs_score) * 100",
        "source_layer": "t1d_rank",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "rs",
        "feature_group": "Momentum_RS",
        "description": "Composite relative strength: 0.4*3m + 0.2*6m + 0.2*9m + 0.2*12m momentum",
        "formula_summary": "0.4*mom_63d + 0.2*mom_126d + 0.2*mom_189d + 0.2*mom_252d",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "rs_ma",
        "feature_group": "Momentum_RS",
        "description": "10-day moving average of RS score",
        "formula_summary": "SMA(rs, 10)",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "rs_delta",
        "feature_group": "Momentum_RS",
        "description": "1-day percentage change of RS score",
        "formula_summary": "(rs - lag(rs, 1)) / abs(lag(rs, 1)) * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "rs_ma_delta",
        "feature_group": "Momentum_RS",
        "description": "1-day percentage change of RS moving average",
        "formula_summary": "(rs_ma - lag(rs_ma, 1)) / abs(lag(rs_ma, 1)) * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "mom_21d",
        "feature_group": "Momentum_RS",
        "description": "21-day price momentum (return)",
        "formula_summary": "(close / lag(close, 21) - 1) * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "mom_63d",
        "feature_group": "Momentum_RS",
        "description": "63-day price momentum (~3 month)",
        "formula_summary": "(close / lag(close, 63) - 1) * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "mom_126d",
        "feature_group": "Momentum_RS",
        "description": "126-day price momentum (~6 month)",
        "formula_summary": "(close / lag(close, 126) - 1) * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "mom_189d",
        "feature_group": "Momentum_RS",
        "description": "189-day price momentum (~9 month)",
        "formula_summary": "(close / lag(close, 189) - 1) * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "mom_252d",
        "feature_group": "Momentum_RS",
        "description": "252-day price momentum (~12 month, excludes most recent month)",
        "formula_summary": "(close / lag(close, 252) - 1) * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "rs_velocity",
        "feature_group": "Momentum_RS",
        "description": "Rate of change of RS score over 5 days",
        "formula_summary": "(rs - lag(rs, 5)) / 5",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "price_accel_10d",
        "feature_group": "Momentum_RS",
        "description": "Price acceleration: difference of 5d and 10d returns",
        "formula_summary": "mom_5d - mom_10d",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "rs_sector_rank",
        "feature_group": "Momentum_RS",
        "description": "RS rank within sector (cross-sectional percentile)",
        "formula_summary": "PERCENT_RANK() OVER (PARTITION BY sector ORDER BY rs) * 100",
        "source_layer": "t1d_rank",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "rs_vs_sector",
        "feature_group": "Momentum_RS",
        "description": "RS score minus sector median RS",
        "formula_summary": "rs - MEDIAN(rs) OVER (PARTITION BY sector)",
        "source_layer": "t1d_rank",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "sector_momentum",
        "feature_group": "Momentum_RS",
        "description": "Median 63d momentum of sector peers",
        "formula_summary": "MEDIAN(mom_63d) OVER (PARTITION BY sector)",
        "source_layer": "t1d_rank",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "rs_industry_rank",
        "feature_group": "Momentum_RS",
        "description": "RS rank within industry group (cross-sectional percentile)",
        "formula_summary": "PERCENT_RANK() OVER (PARTITION BY industry ORDER BY rs) * 100",
        "source_layer": "t1d_rank",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "rs_vs_industry",
        "feature_group": "Momentum_RS",
        "description": "RS score minus industry median RS",
        "formula_summary": "rs - MEDIAN(rs) OVER (PARTITION BY industry)",
        "source_layer": "t1d_rank",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "industry_momentum",
        "feature_group": "Momentum_RS",
        "description": "Median 63d momentum of industry peers",
        "formula_summary": "MEDIAN(mom_63d) OVER (PARTITION BY industry)",
        "source_layer": "t1d_rank",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    # ---- Core_Volume ----
    {
        "feature_name": "vol_ratio",
        "feature_group": "Core_Volume",
        "description": "Today's volume vs 50-day average volume",
        "formula_summary": "volume / SMA(volume, 50)",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "dry_up_volume",
        "feature_group": "Core_Volume",
        "description": "Minimum volume over past 5 days relative to 50-day average (VCP dry-up signal)",
        "formula_summary": "MIN(volume, 5d) / SMA(volume, 50)",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "dry_up_volume_delta",
        "feature_group": "Core_Volume",
        "description": "1-day percentage change of dry_up_volume",
        "formula_summary": "(dry_up_volume - lag(dry_up_volume, 1)) / abs(lag(dry_up_volume, 1)) * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "turnover",
        "feature_group": "Core_Volume",
        "description": "Dollar volume turnover: volume * close",
        "formula_summary": "volume * close",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "volume_acceleration",
        "feature_group": "Core_Volume",
        "description": "5-day volume MA minus 20-day volume MA, normalized by 20-day MA",
        "formula_summary": "(SMA(volume, 5) - SMA(volume, 20)) / SMA(volume, 20)",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "return_1d",
        "feature_group": "Core_Volume",
        "description": "1-day simple return",
        "formula_summary": "(close / lag(close, 1) - 1) * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "return_5d",
        "feature_group": "Core_Volume",
        "description": "5-day simple return",
        "formula_summary": "(close / lag(close, 5) - 1) * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    # ---- Volatility_Ranges ----
    {
        "feature_name": "natr",
        "feature_group": "Volatility_Ranges",
        "description": "Normalized ATR(14): ATR as percentage of close",
        "formula_summary": "ATR(14) / close * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "natr_delta",
        "feature_group": "Volatility_Ranges",
        "description": "1-day percentage change of nATR",
        "formula_summary": "(natr - lag(natr, 1)) / abs(lag(natr, 1)) * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "atr_delta",
        "feature_group": "Volatility_Ranges",
        "description": "1-day percentage change of raw ATR(14) [declared in FEATURE_GROUPS; absent from v0.1 trained artifact]",
        "formula_summary": "(ATR(14) - lag(ATR(14), 1)) / abs(lag(ATR(14), 1)) * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "vcp_ratio",
        "feature_group": "Volatility_Ranges",
        "description": "VCP contraction ratio: recent range / prior range",
        "formula_summary": "range_10d / range_50d",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "vcp_ratio_delta",
        "feature_group": "Volatility_Ranges",
        "description": "1-day percentage change of vcp_ratio",
        "formula_summary": "(vcp_ratio - lag(vcp_ratio, 1)) / abs(lag(vcp_ratio, 1)) * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "consolidation_width",
        "feature_group": "Volatility_Ranges",
        "description": "Price range width during consolidation as percentage",
        "formula_summary": "(high_20d - low_20d) / low_20d * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "consolidation_width_delta",
        "feature_group": "Volatility_Ranges",
        "description": "1-day percentage change of consolidation_width",
        "formula_summary": "(consolidation_width - lag(consolidation_width, 1)) / abs(lag(consolidation_width, 1)) * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "consolidation_duration",
        "feature_group": "Volatility_Ranges",
        "description": "Number of days since last 52-week high",
        "formula_summary": "days since last(close == high_52w)",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "dist_from_52w_high",
        "feature_group": "Volatility_Ranges",
        "description": "Distance from 52-week high as percentage",
        "formula_summary": "(close / high_52w - 1) * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "dist_from_52w_high_delta",
        "feature_group": "Volatility_Ranges",
        "description": "1-day percentage change of dist_from_52w_high",
        "formula_summary": "(dist_from_52w_high - lag(dist_from_52w_high, 1)) / abs(lag(dist_from_52w_high, 1)) * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "dist_from_52w_low",
        "feature_group": "Volatility_Ranges",
        "description": "Distance from 52-week low as percentage",
        "formula_summary": "(close / low_52w - 1) * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "dist_from_52w_low_delta",
        "feature_group": "Volatility_Ranges",
        "description": "1-day percentage change of dist_from_52w_low",
        "formula_summary": "(dist_from_52w_low - lag(dist_from_52w_low, 1)) / abs(lag(dist_from_52w_low, 1)) * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "low_52w_delta",
        "feature_group": "Volatility_Ranges",
        "description": "1-day percentage change of 52-week low price",
        "formula_summary": "(low_52w - lag(low_52w, 1)) / abs(lag(low_52w, 1)) * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "high_52w_delta",
        "feature_group": "Volatility_Ranges",
        "description": "1-day percentage change of 52-week high price",
        "formula_summary": "(high_52w - lag(high_52w, 1)) / abs(lag(high_52w, 1)) * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "dist_from_20d_high",
        "feature_group": "Volatility_Ranges",
        "description": "Distance from 20-day high as percentage",
        "formula_summary": "(close / highest_high_20d - 1) * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "dist_from_20d_high_delta",
        "feature_group": "Volatility_Ranges",
        "description": "1-day percentage change of dist_from_20d_high",
        "formula_summary": "(dist_from_20d_high - lag(dist_from_20d_high, 1)) / abs(lag(dist_from_20d_high, 1)) * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "highest_high_20d_delta",
        "feature_group": "Volatility_Ranges",
        "description": "1-day percentage change of rolling 20-day high",
        "formula_summary": "(highest_high_20d - lag(highest_high_20d, 1)) / abs(lag(highest_high_20d, 1)) * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "dist_from_20d_low",
        "feature_group": "Volatility_Ranges",
        "description": "Distance from 20-day low as percentage",
        "formula_summary": "(close / lowest_low_20d - 1) * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "dist_from_20d_low_delta",
        "feature_group": "Volatility_Ranges",
        "description": "1-day percentage change of dist_from_20d_low",
        "formula_summary": "(dist_from_20d_low - lag(dist_from_20d_low, 1)) / abs(lag(dist_from_20d_low, 1)) * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "lowest_low_20d_delta",
        "feature_group": "Volatility_Ranges",
        "description": "1-day percentage change of rolling 20-day low",
        "formula_summary": "(lowest_low_20d - lag(lowest_low_20d, 1)) / abs(lag(lowest_low_20d, 1)) * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    # ---- Technical_Oscillators ----
    {
        "feature_name": "rsi_14",
        "feature_group": "Technical_Oscillators",
        "description": "RSI(14) oscillator",
        "formula_summary": "RSI(14) — Wilder smoothing",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "rsi_14_delta",
        "feature_group": "Technical_Oscillators",
        "description": "1-day percentage change of RSI(14)",
        "formula_summary": "(rsi_14 - lag(rsi_14, 1)) / abs(lag(rsi_14, 1)) * 100",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "is_green_day",
        "feature_group": "Technical_Oscillators",
        "description": "Binary flag: close > open",
        "formula_summary": "1 if close > open else 0",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "BOOLEAN",
        "is_categorical": False,
    },
    {
        "feature_name": "green_days_ratio_20d",
        "feature_group": "Technical_Oscillators",
        "description": "Proportion of green days over past 20 bars",
        "formula_summary": "SUM(is_green_day, 20) / 20",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "breakout",
        "feature_group": "Technical_Oscillators",
        "description": "Binary flag: SEPA breakout criteria met on this bar",
        "formula_summary": "trend_ok AND vol_ok AND price breakout above pivot",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "BOOLEAN",
        "is_categorical": False,
    },
    {
        "feature_name": "breakout_momentum",
        "feature_group": "Technical_Oscillators",
        "description": "Price gain from prior close to breakout close",
        "formula_summary": "(close / lag(close, 1) - 1) * 100 on breakout day",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "immediate_thrust",
        "feature_group": "Technical_Oscillators",
        "description": "Intraday thrust on breakout: (close - open) / open * 100",
        "formula_summary": "(close - open) / open * 100 on breakout day",
        "source_layer": "t2_sql",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    # ---- Fundamentals ----
    {
        "feature_name": "eps_diluted",
        "feature_group": "Fundamentals",
        "description": "Diluted EPS (most recent quarter)",
        "formula_summary": "net_income / diluted_shares_outstanding",
        "source_layer": "d2_view",
        "source_table": "v_d2_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "revenue_growth_yoy",
        "feature_group": "Fundamentals",
        "description": "Year-over-year revenue growth rate",
        "formula_summary": "(revenue_ttm / revenue_ttm_1y - 1) * 100",
        "source_layer": "d2_view",
        "source_table": "v_d2_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "eps_growth_yoy",
        "feature_group": "Fundamentals",
        "description": "Year-over-year EPS growth rate",
        "formula_summary": "(eps_ttm / eps_ttm_1y - 1) * 100",
        "source_layer": "d2_view",
        "source_table": "v_d2_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "net_income_growth_yoy",
        "feature_group": "Fundamentals",
        "description": "Year-over-year net income growth rate",
        "formula_summary": "(net_income_ttm / net_income_ttm_1y - 1) * 100",
        "source_layer": "d2_view",
        "source_table": "v_d2_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "eps_accel",
        "feature_group": "Fundamentals",
        "description": "EPS growth acceleration: recent quarter growth minus prior quarter growth",
        "formula_summary": "eps_growth_q1 - eps_growth_q2",
        "source_layer": "d2_view",
        "source_table": "v_d2_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "revenue_accel",
        "feature_group": "Fundamentals",
        "description": "Revenue growth acceleration: recent quarter growth minus prior quarter growth",
        "formula_summary": "rev_growth_q1 - rev_growth_q2",
        "source_layer": "d2_view",
        "source_table": "v_d2_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "revenue_cagr_3y",
        "feature_group": "Fundamentals",
        "description": "3-year revenue compound annual growth rate",
        "formula_summary": "(revenue_ttm / revenue_ttm_3y)^(1/3) - 1",
        "source_layer": "d2_view",
        "source_table": "v_d2_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "eps_stability_score",
        "feature_group": "Fundamentals",
        "description": "Consistency of EPS growth over past 8 quarters (1 - CV)",
        "formula_summary": "1 - std(eps_growth_8q) / mean(eps_growth_8q)",
        "source_layer": "d2_view",
        "source_table": "v_d2_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "debt_to_equity",
        "feature_group": "Fundamentals",
        "description": "Total debt / total equity",
        "formula_summary": "total_debt / total_equity",
        "source_layer": "d2_view",
        "source_table": "v_d2_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "current_ratio",
        "feature_group": "Fundamentals",
        "description": "Current assets / current liabilities",
        "formula_summary": "current_assets / current_liabilities",
        "source_layer": "d2_view",
        "source_table": "v_d2_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "gross_margin",
        "feature_group": "Fundamentals",
        "description": "Gross profit margin (TTM)",
        "formula_summary": "gross_profit_ttm / revenue_ttm * 100",
        "source_layer": "d2_view",
        "source_table": "v_d2_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "operating_margin",
        "feature_group": "Fundamentals",
        "description": "Operating income margin (TTM)",
        "formula_summary": "operating_income_ttm / revenue_ttm * 100",
        "source_layer": "d2_view",
        "source_table": "v_d2_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "roe",
        "feature_group": "Fundamentals",
        "description": "Return on equity (TTM)",
        "formula_summary": "net_income_ttm / avg_equity * 100",
        "source_layer": "d2_view",
        "source_table": "v_d2_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "roa",
        "feature_group": "Fundamentals",
        "description": "Return on assets (TTM)",
        "formula_summary": "net_income_ttm / avg_total_assets * 100",
        "source_layer": "d2_view",
        "source_table": "v_d2_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "fcf_margin",
        "feature_group": "Fundamentals",
        "description": "Free cash flow margin (TTM)",
        "formula_summary": "fcf_ttm / revenue_ttm * 100",
        "source_layer": "d2_view",
        "source_table": "v_d2_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "earnings_quality_score",
        "feature_group": "Fundamentals",
        "description": "Composite earnings quality: FCF/net_income ratio",
        "formula_summary": "fcf_ttm / net_income_ttm",
        "source_layer": "d2_view",
        "source_table": "v_d2_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "gross_margin_trend",
        "feature_group": "Fundamentals",
        "description": "Gross margin improvement over past 4 quarters",
        "formula_summary": "gross_margin_q1 - gross_margin_q4",
        "source_layer": "d2_view",
        "source_table": "v_d2_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "days_since_report",
        "feature_group": "Fundamentals",
        "description": "Calendar days since most recent earnings report",
        "formula_summary": "date - last_report_date",
        "source_layer": "d2_view",
        "source_table": "v_d2_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "pe_ratio",
        "feature_group": "Fundamentals",
        "description": "Price-to-earnings ratio",
        "formula_summary": "close / eps_ttm",
        "source_layer": "d2_view",
        "source_table": "v_d2_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "ps_ratio",
        "feature_group": "Fundamentals",
        "description": "Price-to-sales ratio",
        "formula_summary": "market_cap / revenue_ttm",
        "source_layer": "d2_view",
        "source_table": "v_d2_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "pb_ratio",
        "feature_group": "Fundamentals",
        "description": "Price-to-book ratio",
        "formula_summary": "close / book_value_per_share",
        "source_layer": "d2_view",
        "source_table": "v_d2_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    # ---- Fast_Alphas ----
    {
        "feature_name": "alpha001",
        "feature_group": "Fast_Alphas",
        "description": "WQ101 Alpha#1: signed power of daily return rank",
        "formula_summary": "sign(stddev(return,20)) * (-1 * rank(return_1d)^2)",
        "source_layer": "t1c_alpha_xs",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "alpha002",
        "feature_group": "Fast_Alphas",
        "description": "WQ101 Alpha#2: correlation of rank(volume change) with rank(close/open)",
        "formula_summary": "-1 * corr(rank(delta(log(volume),2)), rank((close-open)/open), 6)",
        "source_layer": "t2b_alpha_ts",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "alpha004",
        "feature_group": "Fast_Alphas",
        "description": "WQ101 Alpha#4: negative rank of low over 9 days",
        "formula_summary": "-1 * ts_rank(rank(low), 9)",
        "source_layer": "t2b_alpha_ts",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "alpha006",
        "feature_group": "Fast_Alphas",
        "description": "WQ101 Alpha#6: negative correlation of open with volume",
        "formula_summary": "-1 * corr(open, volume, 10)",
        "source_layer": "t2b_alpha_ts",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "alpha009",
        "feature_group": "Fast_Alphas",
        "description": "WQ101 Alpha#9: conditional close delta based on trend",
        "formula_summary": "if min(delta(close,1),5)>0 then delta(close,1) elif max<0 then delta else -delta",
        "source_layer": "t2b_alpha_ts",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "alpha011",
        "feature_group": "Fast_Alphas",
        "description": "WQ101 Alpha#11: sum of rank(vwap-close) and rank(volume delta)",
        "formula_summary": "rank(ts_max(vwap-close,3)) + rank(ts_min(vwap-close,3)) * rank(delta(volume,3))",
        "source_layer": "t1c_alpha_xs",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "alpha012",
        "feature_group": "Fast_Alphas",
        "description": "WQ101 Alpha#12: sign of volume delta times negative close delta",
        "formula_summary": "sign(delta(volume,1)) * (-1 * delta(close,1))",
        "source_layer": "t2b_alpha_ts",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "alpha013",
        "feature_group": "Fast_Alphas",
        "description": "WQ101 Alpha#13: negative rank of covariance of rank(return) with rank(volume)",
        "formula_summary": "-1 * rank(cov(rank(close), rank(volume), 5))",
        "source_layer": "t1c_alpha_xs",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "alpha015",
        "feature_group": "Fast_Alphas",
        "description": "WQ101 Alpha#15: negative sum of rank correlations of high with volume",
        "formula_summary": "-1 * sum(rank(corr(rank(high), rank(volume), 3)), 3)",
        "source_layer": "t1c_alpha_xs",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "alpha041",
        "feature_group": "Fast_Alphas",
        "description": "WQ101 Alpha#41: rank of vwap power vs close",
        "formula_summary": "rank(vwap^0.5 * high) - rank(close^0.5)",
        "source_layer": "t1c_alpha_xs",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "alpha046",
        "feature_group": "Fast_Alphas",
        "description": "WQ101 Alpha#46: mean-reversion signal from moving average spread",
        "formula_summary": "if (mean(close,20)-mean(close,10))/(mean(close,20)) > 0.25 then -1 ...",
        "source_layer": "t2b_alpha_ts",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "alpha049",
        "feature_group": "Fast_Alphas",
        "description": "WQ101 Alpha#49: conditional close delta based on long-run mean-reversion",
        "formula_summary": "conditional on decay_linear(close spread, 10)",
        "source_layer": "t2b_alpha_ts",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "alpha054",
        "feature_group": "Fast_Alphas",
        "description": "WQ101 Alpha#54: negative rank of open-low vs close-high spread",
        "formula_summary": "-1 * (low - close) * open^5 / ((low - high) * close^5)",
        "source_layer": "t2b_alpha_ts",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "alpha060",
        "feature_group": "Fast_Alphas",
        "description": "WQ101 Alpha#60: linear combination of rank(return) and rank(price position in range)",
        "formula_summary": "-1 * (2*rank(scale(corr(rank(volume),rank(vwap),6))) - rank(scale(...)))",
        "source_layer": "t1c_alpha_xs",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "alpha101",
        "feature_group": "Fast_Alphas",
        "description": "WQ101 Alpha#101: open-close spread normalized by high-low range",
        "formula_summary": "(close - open) / (high - low + 1e-6)",
        "source_layer": "t2b_alpha_ts",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    # ---- M03_Regime ----
    {
        "feature_name": "m03_score",
        "feature_group": "M03_Regime",
        "description": "M03 composite macro regime score (0-100)",
        "formula_summary": "weighted avg of trend, liquidity, risk pillars",
        "source_layer": "m03_regime",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "m03_pillar_trend",
        "feature_group": "M03_Regime",
        "description": "M03 trend pillar score: SPY/QQQ/IWM trend alignment",
        "formula_summary": "weighted avg of SPY/QQQ/IWM above-SMA signals",
        "source_layer": "m03_regime",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "m03_pillar_liq",
        "feature_group": "M03_Regime",
        "description": "M03 liquidity pillar score: Fed net liquidity proxy",
        "formula_summary": "normalized(Fed balance - TGA - RRP)",
        "source_layer": "m03_regime",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "m03_pillar_risk",
        "feature_group": "M03_Regime",
        "description": "M03 risk pillar score: VIX-based regime risk",
        "formula_summary": "1 - normalized(VIX)",
        "source_layer": "m03_regime",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "m03_delta_5d",
        "feature_group": "M03_Regime",
        "description": "5-day change in M03 composite score",
        "formula_summary": "m03_score - lag(m03_score, 5)",
        "source_layer": "m03_regime",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "m03_delta_20d",
        "feature_group": "M03_Regime",
        "description": "20-day change in M03 composite score",
        "formula_summary": "m03_score - lag(m03_score, 20)",
        "source_layer": "m03_regime",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
    {
        "feature_name": "m03_regime_vol",
        "feature_group": "M03_Regime",
        "description": "20-day rolling volatility of M03 score",
        "formula_summary": "STDDEV(m03_score, 20)",
        "source_layer": "m03_regime",
        "source_table": "t3_sepa_features",
        "data_type": "DOUBLE",
        "is_categorical": False,
    },
]

# Retired log_ features (removed from v_d2_training in v3.2)
LOG_FEATURE_NAMES = [
    "log_breakout_momentum", "log_price_momentum_curve", "log_RS",
    "log_Price_vs_SMA_50", "log_Price_vs_SMA_200", "log_Price_vs_SMA_150",
    "log_mom_63d", "log_alpha060", "log_alpha009", "log_alpha001",
    "log_vol_ma20", "log_volume_acceleration", "log_Dry_Up_Volume",
    "log_VCP_Ratio_Delta", "log_Dist_From_52W_Low_Delta", "log_Dry_Up_Volume_Delta",
    "log_Dist_From_20D_Low_Delta", "log_Price_vs_SMA_200_Delta", "log_High_52W_Delta",
    "log_RS_Delta", "log_RS_MA_Delta", "log_Price_vs_SMA_50_Delta",
    "log_Price_vs_SMA_150_Delta", "log_Dist_From_20D_High_Delta",
    "log_Dist_From_52W_High_Delta", "log_rs_line_delta", "log_rs_line_lag_delta",
    "log_rs_velocity", "log_nATR", "log_Dist_From_52W_Low", "log_Lowest_Low_20D_Delta",
    "log_turnover_ma20", "log_fcf_margin", "log_debt_to_equity",
    "log_revenue_cagr_3y", "log_gross_margin_trend", "log_eps_growth_yoy",
    "log_net_income_growth_yoy", "log_revenue_growth_yoy", "log_eps_accel",
    "log_revenue_accel", "log_current_ratio", "log_days_since_report", "log_pb_ratio",
    "log_volume_velocity",
]


def run(db_path: Path) -> None:
    meta = json.loads(METADATA_PATH.read_text())
    valid_features: list[str] = meta["valid_features"]
    accuracy: float = meta["test_accuracy"]
    weighted_f1: float = meta["weighted_f1"]
    macro_f1: float = meta["macro_f1"]

    registry = ModelRegistry(db_path=db_path)
    con = duckdb.connect(str(db_path))

    try:
        # Wipe and re-seed to allow safe re-runs after name corrections
        con.execute("DELETE FROM model_feature_sets WHERE feature_set_id = ?", [FEATURE_SET_ID])
        con.execute(
            "DELETE FROM feature_catalog WHERE version_introduced = ? AND version_retired IS NULL",
            [VERSION_INTRODUCED],
        )
        con.execute(
            "DELETE FROM feature_catalog WHERE version_introduced = ? AND version_retired = ?",
            [VERSION_INTRODUCED, VERSION_RETIRED_LOG],
        )

        # 1. Insert active feature definitions
        catalog_rows = [
            (
                d["feature_name"],
                d["feature_name"].replace("_", " ").title(),
                d["description"],
                d["formula_summary"],
                d["source_layer"],
                d["source_table"],
                d.get("data_type", "DOUBLE"),
                d.get("is_categorical", False),
                VERSION_INTRODUCED,
                None,  # version_retired = NULL (active)
            )
            for d in FEATURE_DEFS
        ]
        con.executemany(
            """
            INSERT OR IGNORE INTO feature_catalog (
                feature_name, display_name, description, formula_summary,
                source_layer, source_table, data_type, is_categorical,
                version_introduced, version_retired
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            catalog_rows,
        )
        print(f"[OK] Inserted {len(catalog_rows)} active features into feature_catalog")

        # 2. Insert retired log_ features for historical documentation
        log_rows = [
            (
                name,
                name.replace("_", " ").title(),
                f"Log-transformed version of underlying feature (retired in {VERSION_RETIRED_LOG})",
                "SIGN(x) * LN(1 + ABS(x))",
                "d2_view",
                "v_d2_training",
                "DOUBLE",
                False,
                VERSION_INTRODUCED,
                VERSION_RETIRED_LOG,
            )
            for name in LOG_FEATURE_NAMES
        ]
        con.executemany(
            """
            INSERT OR IGNORE INTO feature_catalog (
                feature_name, display_name, description, formula_summary,
                source_layer, source_table, data_type, is_categorical,
                version_introduced, version_retired
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            log_rows,
        )
        print(f"[OK] Inserted {len(log_rows)} retired log features into feature_catalog")

        # 3. Register feature set: all features declared in FEATURE_GROUPS
        #    (includes atr_delta even though absent from valid_features artifact)
        all_declared = [d["feature_name"] for d in FEATURE_DEFS]
        group_lookup = {d["feature_name"]: d["feature_group"] for d in FEATURE_DEFS}
        fs_rows = [
            (FEATURE_SET_ID, name, group_lookup.get(name), i)
            for i, name in enumerate(all_declared)
        ]
        con.executemany(
            "INSERT OR IGNORE INTO model_feature_sets "
            "(feature_set_id, feature_name, feature_group, ordinal) VALUES (?, ?, ?, ?)",
            fs_rows,
        )
        print(f"[OK] Registered feature set '{FEATURE_SET_ID}' ({len(fs_rows)} features)")

        # 4. Register model version in models table
        git_sha = ModelRegistry.get_git_sha()
        existing = con.execute(
            "SELECT COUNT(*) FROM models WHERE version_id = ?", [MODEL_VERSION_ID]
        ).fetchone()[0]

        if existing:
            print(f"[SKIP] '{MODEL_VERSION_ID}' already in models table — no changes made")
        else:
            specs = {
                "features": valid_features,
                "hyperparameters": {
                    "objective": "multi:softprob",
                    "num_class": 4,
                    "max_depth": 4,
                    "learning_rate": 0.05,
                    "subsample": 0.8,
                    "colsample_bytree": 0.8,
                },
                "training_config": {
                    "train_samples": meta["train_samples"],
                    "val_samples": meta["val_samples"],
                    "test_samples": meta["test_samples"],
                    "feature_version": meta["feature_version"],
                },
            }
            registry.register_version(
                version_id=MODEL_VERSION_ID,
                specs=specs,
                status="prod",
                feature_version=meta["feature_version"],
                dataset_rows=meta["train_samples"] + meta["val_samples"] + meta["test_samples"],
                accuracy=accuracy,
                weighted_f1=weighted_f1,
                macro_f1=macro_f1,
                feature_set_id=FEATURE_SET_ID,
                git_sha=git_sha,
                model_type="classifier",
            )
            print(f"[OK] Registered '{MODEL_VERSION_ID}' as prod (acc={accuracy:.4f})")

    finally:
        con.close()


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Seed feature catalog and register M01_baseline v0.1")
    parser.add_argument("--db", type=Path, default=DB_PATH)
    args = parser.parse_args()

    print(f"Populating feature catalog in {args.db} ...")
    run(args.db)
    print("Done.")
