"""Permutation null backtest for m01_prototype_may/v2_gated.

Step §2 of docs/plans/eval_14c_parallel_session_instructions.md.

Approach
--------
The plan calls for a per-date signal shuffle, then a full backtest per
permutation. The production BackTrader runner takes ~30s per call → 8h at
1000 perms. We use the vectorized engine instead so the same null can run
in ~10-20 min for 100 perms (fast mode per plan).

Signals are regenerated by re-scoring each fold's test window with that
fold's frozen booster (no leakage — the booster never saw its test slice).
Categorical columns are remapped from the training-time `categorical_mapping.json`.
"""
from __future__ import annotations

import json
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import duckdb
import xgboost as xgb

import config
from src.evaluation.permutation_null import permutation_null_backtest
from src.backtest.vectorized_backtest import VectorizedSEPABacktest
from src.evaluation.bootstrap import sharpe_from_trades


MODEL_DIR = ROOT / "models" / "m01_prototype_may" / "v2_gated"
DB_PATH = config.DUCKDB_PATH
OUT = MODEL_DIR / "evaluation" / "full_eval" / "permutation_null.json"

# Plan calls for "deep mode 1000 perms" → ~8h on the BackTrader runner.
# We use the vectorized engine; bumping N_PERMS to 200 keeps runtime under
# ~30 min while still giving us 0.5 pct-point resolution on the null.
N_PERMS = int(__import__("os").environ.get("N_PERMS", "200"))

PRODUCTION_CLASS_IDX = 3  # 4-class Home Run = last bucket

# Mirror VectorizedSEPABacktest defaults so observed and null share an engine.
BACKTEST_KW = dict(
    min_prob_elite=0.15,
    max_positions_per_day=3,
    ranking_lookback_days=10,
    stop_loss_pct=0.10,
    sma_exit_period=50,
    warmup_days=10,
    commission_pct=0.001,
    slippage_pct=0.001,
    initial_cash=100_000.0,
    position_size_pct=0.10,
    max_hold_days=252,
)


def _load_categorical_mapping() -> dict:
    path = MODEL_DIR / "categorical_mapping.json"
    return json.loads(path.read_text())


def _load_metadata() -> dict:
    return json.loads((MODEL_DIR / "metadata.json").read_text())


def _build_fold_signals(con: duckdb.DuckDBPyConnection,
                       fold_dir: Path,
                       feature_cols: list[str],
                       cat_mapping: dict,
                       feature_version: str,
                       min_date: str) -> pd.DataFrame:
    """Score this fold's test window with its frozen model. Returns (date, ticker, signal)."""
    spec = json.loads((fold_dir / "spec.json").read_text())
    booster = xgb.Booster()
    booster.load_model(str(fold_dir / "model.json"))

    # Use d2_training_cache (materialized v_d2_training) — view is a heavy JOIN
    # over t3_sepa_features and OOMs on bare SELECT *. The cache is ~70x faster.
    rows = con.execute(
        """
        SELECT *
        FROM d2_training_cache
        WHERE feature_version = ?
          AND date >= ?
          AND date BETWEEN ? AND ?
          AND mfe_pct IS NOT NULL
        """,
        [feature_version, min_date, spec["test_start"], spec["test_end"]],
    ).df()
    if rows.empty:
        return pd.DataFrame(columns=["date", "ticker", "signal"])

    rows.columns = [c.lower() if c not in cat_mapping else c for c in rows.columns]
    # Some feature names in metadata are TitleCase (cross-sectional ranks). v_d2_training
    # returns lowercase; the trainer relies on `_attach_titlecase_columns` upstream. Map.
    titlecase_map = {
        "rs_sector_rank": "RS_Sector_Rank",
        "rs_vs_sector": "RS_vs_Sector",
        "sector_momentum": "Sector_Momentum",
        "rs_industry_rank": "RS_Industry_Rank",
        "rs_vs_industry": "RS_vs_Industry",
        "industry_momentum": "Industry_Momentum",
        "rs_universe_rank": "RS_Universe_Rank",
    }
    rows = rows.rename(columns=titlecase_map)

    missing = [c for c in feature_cols if c not in rows.columns]
    if missing:
        raise RuntimeError(f"v_d2_training missing features for fold {spec['fold_idx']}: {missing[:5]}")

    X = rows[feature_cols].copy()

    # Apply categorical mapping (training categories only — out-of-vocab → NaN).
    for col, categories in cat_mapping.items():
        if col in X.columns:
            X[col] = pd.Categorical(X[col].astype(str), categories=categories)
    X = X.replace([np.inf, -np.inf], np.nan)

    dmat = xgb.DMatrix(X, enable_categorical=True)
    proba = np.asarray(booster.predict(dmat))
    if proba.ndim != 2 or proba.shape[1] <= PRODUCTION_CLASS_IDX:
        raise RuntimeError(
            f"Unexpected proba shape {proba.shape} for fold {spec['fold_idx']}"
        )
    prob_elite = proba[:, PRODUCTION_CLASS_IDX]

    out = pd.DataFrame(
        {
            "date": pd.to_datetime(rows["date"]),
            "ticker": rows["ticker"].astype(str),
            "signal": prob_elite,
        }
    )
    print(f"  fold {spec['fold_idx']}: {len(out)} rows, {out['date'].nunique()} dates")
    return out


def _load_prices(con, tickers, start, end):
    df = con.execute(
        """
        SELECT ticker, date, open, high, low, close
        FROM price_data
        WHERE ticker = ANY(?)
          AND date >= ? AND date <= ?
        ORDER BY ticker, date
        """,
        [tickers, start, end],
    ).df()
    df["date"] = pd.to_datetime(df["date"])
    return df


def _signals_to_scores(signals_df: pd.DataFrame) -> pd.DataFrame:
    """VectorizedSEPABacktest expects (date, ticker, prob_elite, calibrated_score)."""
    out = signals_df.rename(columns={"signal": "prob_elite"}).copy()
    out["calibrated_score"] = out["prob_elite"]
    return out


def _backtest_metric(signals_df: pd.DataFrame, prices_df: pd.DataFrame,
                     start: str, end: str) -> dict:
    scores = _signals_to_scores(signals_df)
    bt = VectorizedSEPABacktest(
        model_path="<unused>",
        db_path=str(DB_PATH),
        start_date=start,
        end_date=end,
        precomputed_scores=scores,
        precomputed_prices=prices_df,
        **BACKTEST_KW,
    )
    trades = bt.run()
    if trades.empty:
        return {"sharpe_ratio": float("nan"), "n_trades": 0, "total_return": 0.0}
    # Sharpe approximation from trade-level PnL — same convention bootstrap_ci uses.
    pnl_pct = trades["pnl_pct"].to_numpy() * 100.0
    trades_for_sharpe = pd.DataFrame({"pnl_percent": pnl_pct, "exit_date": trades["exit_date"]})
    sharpe = sharpe_from_trades(trades_for_sharpe)
    return {
        "sharpe_ratio": float(sharpe) if sharpe == sharpe else float("nan"),
        "n_trades": int(len(trades)),
        "total_return": float(pnl_pct.sum()),
    }


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    meta = _load_metadata()
    cat_mapping = _load_categorical_mapping()
    feature_cols = meta["valid_features"]
    feature_version = meta["feature_version"]
    min_date = meta["min_date"]

    fold_dirs = sorted((MODEL_DIR / "folds").glob("fold_*"))
    print(f"Re-scoring {len(fold_dirs)} folds...")

    con = duckdb.connect(str(DB_PATH), read_only=True)
    try:
        per_fold_signals = []
        for fd in fold_dirs:
            sig = _build_fold_signals(con, fd, feature_cols, cat_mapping,
                                       feature_version, min_date)
            if not sig.empty:
                per_fold_signals.append(sig)
        signals_df = pd.concat(per_fold_signals, ignore_index=True)
        # Per-ticker dedup across overlapping folds (shouldn't happen for anchored WF, but safe).
        signals_df = signals_df.sort_values(["date", "ticker"]).drop_duplicates(
            subset=["date", "ticker"], keep="last"
        )
        print(f"Combined signals: {len(signals_df)} rows, {signals_df['date'].nunique()} dates, "
              f"{signals_df['ticker'].nunique()} tickers")

        start = signals_df["date"].min().strftime("%Y-%m-%d")
        end = signals_df["date"].max().strftime("%Y-%m-%d")
        tickers = signals_df["ticker"].unique().tolist()

        prices = _load_prices(con, tickers, start, end)
        print(f"Loaded {len(prices)} price rows for {prices['ticker'].nunique()} tickers ({start} -> {end})")
    finally:
        con.close()

    # Sanity check observed metric before paying for the null distribution.
    t0 = time.time()
    observed_metrics = _backtest_metric(signals_df, prices, start, end)
    print(f"Observed backtest: {observed_metrics} (took {time.time()-t0:.1f}s)")

    def backtest_fn(df: pd.DataFrame) -> dict:
        return _backtest_metric(df, prices, start, end)

    print(f"Running permutation null with N_PERMS={N_PERMS} ...")
    t0 = time.time()
    result = permutation_null_backtest(
        signals_df=signals_df,
        backtest_fn=backtest_fn,
        n_permutations=N_PERMS,
        seed=42,
        signal_col="signal",
        date_col="date",
        metric_key="sharpe_ratio",
        one_sided=True,
    )
    elapsed = time.time() - t0
    print(f"Permutation null done in {elapsed/60:.1f} min")

    payload = {
        "engine": "VectorizedSEPABacktest (fast)",
        "n_permutations": N_PERMS,
        "elapsed_minutes": round(elapsed / 60, 2),
        "observed_metrics": observed_metrics,
        "result": result,
    }
    OUT.write_text(json.dumps(payload, indent=2, default=str))
    print(f"Wrote {OUT}")
    print(f"observed_sharpe={result['observed_metric']:.4f}, "
          f"null_median={result['null_median']:.4f}, "
          f"percentile={result['percentile']:.1f}, "
          f"gate={result['gate']['status']}")


if __name__ == "__main__":
    main()
