"""
Dashboard ML Reports Module
===========================

Provides report page rendering functions for the TradeOps Dashboard.

Pages load PRE-GENERATED report files (JSON/CSV) from models/ directory.
The reports are generated by the CLI (python model.py m01 --report).

This is fast because the dashboard only loads small JSON files,
not raw parquet data.
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px
from pathlib import Path
import json
import glob
from datetime import datetime


# =============================================================================
# DATA LOADING HELPERS (Load pre-generated reports, not raw data)
# =============================================================================

@st.cache_data(ttl=60)
def load_model_config(model_name: str):
    """Load model configuration JSON (contains validation metrics)."""
    path = Path(f'models/{model_name.lower()}_config.json')
    if path.exists():
        with open(path, 'r') as f:
            return json.load(f)
    return None


@st.cache_data(ttl=60)
def load_feature_importance(model_name: str):
    """Load feature importance CSV."""
    path = Path(f'models/feature_importance_{model_name.lower()}.csv')
    if path.exists():
        return pd.read_csv(path)
    return None


@st.cache_data(ttl=60)
def load_latest_report(model_name: str):
    """Load the latest markdown report for a model."""
    pattern = f'models/model_report_{model_name.upper()}_*.md'
    files = sorted(glob.glob(pattern), reverse=True)
    if files:
        with open(files[0], 'r', encoding='utf-8') as f:
            return f.read(), files[0]
    return None, None


@st.cache_data(ttl=60)
def load_d1_report():
    """Load D1 analysis report (trade physics pre-computed stats)."""
    path = Path('models/d1_analysis.json')
    if path.exists():
        with open(path, 'r') as f:
            return json.load(f)
    return None


@st.cache_data(ttl=60)
def load_d3_summary():
    """Load D3 triple barrier summary (pre-computed stats)."""
    # Check both possible paths
    paths = [
        Path('data/ml/d3_summary.json'),
        Path('models/d3_summary.json')
    ]
    for path in paths:
        if path.exists():
            with open(path, 'r') as f:
                return json.load(f)
    return None


# =============================================================================
# PAGE 1: D1 ANALYSIS (Load pre-generated stats)
# =============================================================================

def render_d1_analysis():
    """Render D1 Analysis page - Trade Physics (from pre-generated report)."""
    from src.viz_library import (
        create_mae_mfe_scatter,
        create_e_ratio_histogram,
        create_time_to_peak_histogram
    )

    st.title("📊 D1 Analysis: Trade Physics")
    st.markdown("Trade characteristics: MAE/MFE, E-Ratio, crash rates.")

    # Try to load pre-generated report
    d1_report = load_d1_report()

    if d1_report is None:
        st.warning("D1 Analysis report not generated yet.")
        st.markdown("""
        **To generate:**
        ```bash
        python model.py m01 --steps train --report
        ```

        This will pre-compute trade physics and save to `models/d1_analysis.json`.
        """)

        # Fallback: show what the report WILL contain
        st.info("Once generated, this page will show:")
        col1, col2, col3, col4 = st.columns(4)
        with col1:
            st.metric("Total Trades", "N/A")
        with col2:
            st.metric("Median MFE", "N/A")
        with col3:
            st.metric("Median MAE", "N/A")
        with col4:
            st.metric("Crash Rate", "N/A")
        return

    # Display pre-computed metrics
    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.metric("Total Trades", f"{d1_report.get('total_trades', 0):,}")
    with col2:
        st.metric("Median MFE", f"{d1_report.get('median_mfe', 0):.1f}%")
    with col3:
        st.metric("Median MAE", f"{d1_report.get('median_mae', 0):.1f}%")
    with col4:
        st.metric("Median E-Ratio", f"{d1_report.get('median_e_ratio', 0):.2f}")

    # Crash rate from report
    st.markdown("### Crash Rate Analysis")
    crash_rate = d1_report.get('crash_rate', 0)
    survived_rate = 100 - crash_rate

    col1, col2 = st.columns(2)
    with col1:
        st.metric("Crashed", f"{crash_rate:.1f}%", delta=None)
    with col2:
        st.metric("Survived", f"{survived_rate:.1f}%", delta=None)

    st.info(f"Using stop multiplier: {d1_report.get('stop_multiplier', 2.0)}x nATR")

    # NEW: MAE/MFE Scatter Plot
    if 'mae_mfe_scatter' in d1_report and len(d1_report['mae_mfe_scatter']) > 0:
        st.markdown("---")
        st.markdown("### MAE/MFE Analysis")
        st.markdown("Maximum Adverse/Favorable Excursion scatter with E-Ratio reference lines. "
                   "Trades above the **E-Ratio 3.0** line indicate strong edge.")

        try:
            fig = create_mae_mfe_scatter(d1_report['mae_mfe_scatter'])
            st.plotly_chart(fig, use_container_width=True)
        except Exception as e:
            st.error(f"Error rendering MAE/MFE scatter: {e}")

    # NEW: E-Ratio Distribution
    if 'e_ratio_distribution' in d1_report and len(d1_report['e_ratio_distribution']) > 0:
        st.markdown("---")
        st.markdown("### E-Ratio Distribution")
        pct_above = d1_report.get('e_ratio_gt_3_pct', 0)
        st.markdown(f"E-Ratio = MFE / |MAE| measures upside/downside asymmetry. "
                   f"**{pct_above:.1f}%** of trades exceed the 3.0 benchmark.")

        try:
            fig = create_e_ratio_histogram(d1_report['e_ratio_distribution'], benchmark=3.0)
            st.plotly_chart(fig, use_container_width=True)
        except Exception as e:
            st.error(f"Error rendering E-Ratio histogram: {e}")

    # NEW: Time to Peak
    if 'time_to_peak' in d1_report and len(d1_report['time_to_peak']) > 0:
        st.markdown("---")
        st.markdown("### Time to Peak (MFE)")
        median_days = pd.Series(d1_report['time_to_peak']).median()
        st.markdown(f"Days to reach Maximum Favorable Excursion. "
                   f"Median: **{median_days:.0f} days**. This informs optimal holding periods.")

        try:
            fig = create_time_to_peak_histogram(d1_report['time_to_peak'])
            st.plotly_chart(fig, use_container_width=True)
        except Exception as e:
            st.error(f"Error rendering time-to-peak histogram: {e}")


# =============================================================================
# PAGE 2: M01 REPORT (Load config JSON)
# =============================================================================

def render_m01_report():
    """Render M01 Report page - loads pre-generated model config."""
    from src.viz_library import (
        create_decile_bar_chart,
        create_actual_vs_predicted_scatter,
        create_feature_importance_waterfall,
        create_residual_plot
    )

    st.title("📈 M01 Report: Return Regressor")
    st.markdown("Walk-forward validation results and feature importance.")

    # Load from pre-generated config
    config = load_model_config('m01')
    importance_df = load_feature_importance('m01')

    if config is None:
        st.warning("M01 model not trained yet.")
        st.markdown("""
        **To train and generate report:**
        ```bash
        python model.py m01 --steps train --report
        ```
        """)
        return

    # Model metadata
    st.markdown("### Model Information")
    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric("Model Type", config.get('model_type', 'N/A').upper())
    with col2:
        st.metric("Features", len(config.get('feature_columns', [])))
    with col3:
        created = config.get('created_at', 'N/A')[:10] if config.get('created_at') else 'N/A'
        st.metric("Created", created)

    # Walk-forward results from config
    metrics = config.get('validation_metrics', [])
    if metrics:
        st.markdown("### Walk-Forward Validation Results")

        metrics_df = pd.DataFrame(metrics)

        # Summary stats
        avg_edge = metrics_df['selection_edge'].mean()
        avg_rmse = metrics_df['rmse'].mean()
        positive_folds = (metrics_df['selection_edge'] > 0).sum()
        avg_top = metrics_df['top_decile_mean'].mean()

        col1, col2, col3, col4 = st.columns(4)
        with col1:
            st.metric("Avg Edge", f"{avg_edge:+.2f}%")
        with col2:
            st.metric("Avg RMSE", f"{avg_rmse:.2f}%")
        with col3:
            st.metric("Positive Folds", f"{positive_folds}/{len(metrics_df)}")
        with col4:
            st.metric("Top Decile", f"{avg_top:.2f}%")

        # Table
        st.dataframe(
            metrics_df[['test_year', 'test_samples', 'rmse', 'selection_edge', 'top_decile_mean']].round(2),
            use_container_width=True,
            hide_index=True
        )

        # Edge bar chart
        st.markdown("### Selection Edge Over Time")
        fig = px.bar(
            metrics_df,
            x='test_year',
            y='selection_edge',
            title='Selection Edge by Test Year',
            color='selection_edge',
            color_continuous_scale=['red', 'yellow', 'green'],
            color_continuous_midpoint=0
        )
        fig.add_hline(y=0, line_dash="dash", line_color="gray")
        fig.update_layout(height=350, template='plotly_white')
        st.plotly_chart(fig, use_container_width=True)

    # NEW: Decile Performance Analysis
    if 'decile_performance' in config and len(config['decile_performance']) > 0:
        st.markdown("---")
        st.markdown("### Decile Performance Analysis")
        st.markdown("Mean return % by predicted return decile. Decile 1 = highest predicted returns.")

        try:
            fig = create_decile_bar_chart(config['decile_performance'])
            st.plotly_chart(fig, use_container_width=True)
        except Exception as e:
            st.error(f"Error rendering decile chart: {e}")

    # NEW: Actual vs Predicted Scatter
    if 'predictions_sample' in config and len(config['predictions_sample']) > 0:
        st.markdown("---")
        st.markdown("### Actual vs Predicted Returns")
        st.markdown("Scatter plot of model predictions vs actual outcomes. Points near the diagonal line indicate accurate predictions.")

        try:
            fig = create_actual_vs_predicted_scatter(config['predictions_sample'])
            st.plotly_chart(fig, use_container_width=True)
        except Exception as e:
            st.error(f"Error rendering scatter plot: {e}")

        # NEW: Residual Analysis
        st.markdown("---")
        st.markdown("### Residual Analysis")
        st.markdown("Residuals (actual - predicted) should be randomly distributed around zero with no patterns.")

        try:
            fig = create_residual_plot(config['predictions_sample'])
            st.plotly_chart(fig, use_container_width=True)
        except Exception as e:
            st.error(f"Error rendering residual plot: {e}")

    # NEW: Error Analysis (FOMO vs Toxic)
    if 'error_analysis' in config:
        st.markdown("---")
        st.markdown("### Error Analysis: FOMO vs Toxic")
        st.markdown("**FOMO**: Predicted low, but actual high (missed winners). "
                   "**Toxic**: Predicted high, but actual low (false positives).")

        err = config['error_analysis']
        col1, col2, col3, col4 = st.columns(4)

        with col1:
            st.metric("FOMO Errors", err.get('FOMO', {}).get('count', 0),
                     delta=f"{err.get('FOMO', {}).get('avg_missed_return', 0):.1f}% missed")
        with col2:
            st.metric("Toxic Errors", err.get('Toxic', {}).get('count', 0),
                     delta=f"{err.get('Toxic', {}).get('avg_loss', 0):.1f}% avg")
        with col3:
            st.metric("True Positives", err.get('True_Positive', {}).get('count', 0),
                     delta=f"{err.get('True_Positive', {}).get('avg_return', 0):.1f}% avg")
        with col4:
            st.metric("True Negatives", err.get('True_Negative', {}).get('count', 0),
                     delta=f"{err.get('True_Negative', {}).get('avg_return', 0):.1f}% avg")

    # Feature importance (from CSV) - Enhanced with Waterfall
    if importance_df is not None and len(importance_df) > 0:
        st.markdown("---")
        st.markdown("### Feature Importance")

        top_n = st.slider("Show top N features", 10, 30, 20)

        try:
            fig = create_feature_importance_waterfall(importance_df, top_n=top_n)
            st.plotly_chart(fig, use_container_width=True)
        except Exception as e:
            st.error(f"Error rendering waterfall chart: {e}")


# =============================================================================
# PAGE 3: M02 REPORT (Load config JSON)
# =============================================================================

def render_m02_report():
    """Render M02 Report page - loads pre-generated model config."""
    st.title("🎯 M02 Report: Ignition Classifier")
    st.markdown("Triple barrier classification results.")
    
    config = load_model_config('m02')
    d3_summary = load_d3_summary()
    
    # D3 Summary (pre-computed)
    if d3_summary:
        st.markdown("### Triple Barrier Outcomes")
        
        col1, col2, col3 = st.columns(3)
        with col1:
            tp = d3_summary.get('tp_rate', 0)
            st.metric("Take Profit", f"{tp:.1f}%")
        with col2:
            sl = d3_summary.get('sl_rate', 0)
            st.metric("Stop Loss", f"{sl:.1f}%")
        with col3:
            time_exit = d3_summary.get('time_rate', 0)
            st.metric("Time Exit", f"{time_exit:.1f}%")
        
        # Pie chart
        fig = px.pie(
            values=[tp, sl, time_exit],
            names=['TP', 'SL', 'Time'],
            title='Barrier Outcome Distribution',
            color_discrete_sequence=['green', 'red', 'gray']
        )
        fig.update_layout(height=350)
        st.plotly_chart(fig, use_container_width=True)
    else:
        st.info("D3 summary not found. Run `python model.py m02 --steps label` first.")
    
    # Model metrics from config
    if config:
        st.markdown("### Model Validation Results")
        
        metrics = config.get('validation_metrics', [])
        if metrics:
            metrics_df = pd.DataFrame(metrics)
            
            if 'auc' in metrics_df.columns:
                avg_auc = metrics_df['auc'].mean()
                st.metric("Average AUC", f"{avg_auc:.3f}")
            
            st.dataframe(metrics_df, use_container_width=True, hide_index=True)
    else:
        st.warning("M02 model not trained. Run `python model.py m02 --steps train` first.")


# =============================================================================
# PAGE 4: DUAL-MODEL ANALYSIS
# =============================================================================

def render_dual_model():
    """Render Dual-Model page - Combined M01+M02 analysis."""
    st.title("🔀 Dual-Model Analysis")
    st.markdown("Compare M01 (regression) and M02 (classification) model outputs.")
    
    m01_config = load_model_config('m01')
    m02_config = load_model_config('m02')
    
    col1, col2 = st.columns(2)
    
    with col1:
        st.markdown("### M01 (Regressor)")
        if m01_config:
            metrics = m01_config.get('validation_metrics', [])
            if metrics:
                avg_edge = np.mean([m['selection_edge'] for m in metrics])
                st.metric("Selection Edge", f"{avg_edge:+.2f}%")
                st.metric("Features", len(m01_config.get('feature_columns', [])))
        else:
            st.info("M01 not trained")
    
    with col2:
        st.markdown("### M02 (Classifier)")
        if m02_config:
            metrics = m02_config.get('validation_metrics', [])
            if metrics and 'auc' in metrics[0]:
                avg_auc = np.mean([m['auc'] for m in metrics])
                st.metric("Average AUC", f"{avg_auc:.3f}")
            st.metric("Features", len(m02_config.get('feature_columns', [])))
        else:
            st.info("M02 not trained")
    
    st.markdown("---")
    st.markdown("""
    ### Combined Scoring Strategy
    
    **Dual-Model Approach:**
    1. M01 predicts expected return %
    2. M02 predicts ignition probability
    3. Combined rank uses both signals
    
    **Filter:** M01 Rank ≤ 3 AND M02 Prob > 0.5
    """)


# =============================================================================
# PAGE 5: BACKTEST (Placeholder)
# =============================================================================

def render_backtest():
    """Render Backtest page - placeholder for future implementation."""
    st.title("📊 Backtest Results")
    st.warning("⚠️ Backtest module not yet implemented")
    
    st.markdown("""
    ### Planned Features
    - Equity curve
    - Drawdown analysis
    - Win rate & profit factor
    - Monthly returns heatmap
    
    **To implement:**
    1. Create `src/backtester.py`
    2. Add `python model.py backtest` command
    3. Generate report to `models/backtest_results.json`
    """)
