"""
Dashboard ML Reports Module
===========================

Provides report page rendering functions for the TradeOps Dashboard.

Pages load PRE-GENERATED report files (JSON/CSV) from models/ directory.
The reports are generated by the CLI (python model.py m01 --report).

This is fast because the dashboard only loads small JSON files,
not raw parquet data.
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px
from pathlib import Path
import json
import glob
from datetime import datetime


# =============================================================================
# DATA LOADING HELPERS (Load pre-generated reports, not raw data)
# =============================================================================

@st.cache_data(ttl=300)  # Model configs change infrequently
def load_model_config(model_name: str):
    """Load model configuration JSON (contains validation metrics)."""
    path = Path(f'models/{model_name.lower()}_config.json')
    if path.exists():
        with open(path, 'r') as f:
            return json.load(f)
    return None


@st.cache_data(ttl=300)
def load_feature_importance(model_name: str):
    """Load feature importance CSV."""
    path = Path(f'models/feature_importance_{model_name.lower()}.csv')
    if path.exists():
        return pd.read_csv(path)
    return None


@st.cache_data(ttl=300)
def load_latest_report(model_name: str):
    """Load the latest markdown report for a model."""
    pattern = f'models/model_report_{model_name.upper()}_*.md'
    files = sorted(glob.glob(pattern), reverse=True)
    if files:
        with open(files[0], 'r', encoding='utf-8') as f:
            return f.read(), files[0]
    return None, None


@st.cache_data(ttl=300)
def load_d1_report():
    """Load D1 analysis report (trade physics pre-computed stats)."""
    path = Path('models/d1_analysis.json')
    if path.exists():
        with open(path, 'r') as f:
            return json.load(f)
    return None


@st.cache_data(ttl=300)
def load_d3_summary():
    """Load D3 triple barrier summary (pre-computed stats)."""
    # Check both possible paths
    paths = [
        Path('data/ml/d3_summary.json'),
        Path('models/d3_summary.json')
    ]
    for path in paths:
        if path.exists():
            with open(path, 'r') as f:
                return json.load(f)
    return None


@st.cache_data(ttl=300)  # Increased from 60s to 5min - EDA data changes infrequently
def load_eda_dashboard():
    """Load EDA dashboard JSON (feature screening results).

    Performance: Large JSON file (~5-10MB), cache for 5 minutes to reduce I/O.
    """
    path = Path('models/eda_dashboard.json')
    if path.exists():
        with open(path, 'r') as f:
            return json.load(f)
    return None


@st.cache_data(ttl=60)
def discover_model_versions(model_prefix: str = 'm01') -> list:
    """
    Discover available model versions by scanning for config files.
    
    Looks for files matching pattern: {model_prefix}*_config.json
    Returns list of model names (e.g., ['m01', 'm01_v2', 'm01_bench'])
    """
    pattern = f'models/{model_prefix}*_config.json'
    files = glob.glob(pattern)
    
    versions = []
    for f in files:
        # Extract model name from path (e.g., 'models/m01_v2_config.json' -> 'm01_v2')
        filename = Path(f).stem  # 'm01_v2_config'
        if filename.endswith('_config'):
            model_name = filename[:-7]  # Remove '_config' suffix
            # Verify it has validation metrics (is a trained model)
            try:
                with open(f, 'r') as fp:
                    config = json.load(fp)
                    if 'validation_metrics' in config or 'feature_columns' in config:
                        versions.append(model_name)
            except:
                pass
    
    # Sort with base model first
    versions.sort(key=lambda x: (x != model_prefix, x))
    return versions


# =============================================================================
# PAGE: EDA SUMMARY (Unified EDA Page - Phase 2 Reorganization)
# =============================================================================

def render_eda_summary():
    """
    Unified EDA Summary page with 4 tabs:
    - Tab 1: D1 Trade Physics
    - Tab 2: SEPA Criteria (box plots)
    - Tab 3: D2 Feature Analysis
    - Tab 4: Candidate Profile

    Performance: Data loaded lazily per tab to reduce initial page load time.
    """
    st.title("📊 EDA Summary")
    st.markdown("Comprehensive Exploratory Data Analysis across D1 (Trade Physics) and D2 (Feature Screening).")

    # Create 4 tabs
    tab1, tab2, tab3, tab4 = st.tabs([
        "D1 Trade Physics",
        "SEPA Criteria",
        "D2 Feature Analysis",
        "Candidate Profile"
    ])

    # --- TAB 1: D1 Trade Physics ---
    # Data is loaded ONLY when this tab is rendered (lazy loading via Streamlit)
    with tab1:
        _render_d1_trade_physics()

    # --- TAB 2: SEPA Criteria Analysis ---
    with tab2:
        _render_sepa_criteria()

    # --- TAB 3: D2 Feature Analysis ---
    with tab3:
        _render_d2_feature_analysis()

    # --- TAB 4: Candidate Profile ---
    with tab4:
        _render_candidate_profile()


def _render_d1_trade_physics():
    """Render D1 Trade Physics content (MAE/MFE, E-Ratio, Time to Peak)."""
    from src.viz_library import (
        create_mae_mfe_scatter,
        create_e_ratio_histogram,
        create_time_to_peak_histogram
    )

    st.markdown("### Trade Physics Analysis")
    st.markdown("Maximum Adverse/Favorable Excursion, E-Ratio, and crash rates from historical trades.")

    d1_report = load_d1_report()

    if d1_report is None:
        st.warning("D1 Analysis report not generated yet.")
        st.markdown("""
        **To generate:**
        ```bash
        python model.py m01 --steps train --report
        ```
        """)
        return

    # Metrics
    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.metric("Total Trades", f"{d1_report.get('total_trades', 0):,}")
    with col2:
        st.metric("Median MFE", f"{d1_report.get('median_mfe', 0):.1f}%")
    with col3:
        st.metric("Median MAE", f"{d1_report.get('median_mae', 0):.1f}%")
    with col4:
        st.metric("Median E-Ratio", f"{d1_report.get('median_e_ratio', 0):.2f}")

    # Crash rate
    crash_rate = d1_report.get('crash_rate', 0)
    survived_rate = 100 - crash_rate

    col1, col2 = st.columns(2)
    with col1:
        st.metric("Crashed", f"{crash_rate:.1f}%")
    with col2:
        st.metric("Survived", f"{survived_rate:.1f}%")

    st.info(f"Using stop multiplier: {d1_report.get('stop_multiplier', 2.0)}x nATR")

    # MAE/MFE Scatter
    if 'mae_mfe_scatter' in d1_report and len(d1_report['mae_mfe_scatter']) > 0:
        st.markdown("---")
        st.markdown("### MAE/MFE Analysis")
        try:
            fig = create_mae_mfe_scatter(d1_report['mae_mfe_scatter'])
            st.plotly_chart(fig, use_container_width=True)
        except Exception as e:
            st.error(f"Error rendering MAE/MFE scatter: {e}")

    # E-Ratio Distribution
    if 'e_ratio_distribution' in d1_report and len(d1_report['e_ratio_distribution']) > 0:
        st.markdown("---")
        st.markdown("### E-Ratio Distribution")
        pct_above = d1_report.get('e_ratio_gt_3_pct', 0)
        st.markdown(f"E-Ratio = MFE / |MAE|. **{pct_above:.1f}%** of trades exceed the 3.0 benchmark.")
        try:
            fig = create_e_ratio_histogram(d1_report['e_ratio_distribution'], benchmark=3.0)
            st.plotly_chart(fig, use_container_width=True)
        except Exception as e:
            st.error(f"Error rendering E-Ratio histogram: {e}")

    # Time to Peak
    if 'time_to_peak' in d1_report and len(d1_report['time_to_peak']) > 0:
        st.markdown("---")
        st.markdown("### Time to Peak (MFE)")
        median_days = pd.Series(d1_report['time_to_peak']).median()
        st.markdown(f"Days to reach Maximum Favorable Excursion. Median: **{median_days:.0f} days**.")
        try:
            fig = create_time_to_peak_histogram(d1_report['time_to_peak'])
            st.plotly_chart(fig, use_container_width=True)
        except Exception as e:
            st.error(f"Error rendering time-to-peak histogram: {e}")


def _render_sepa_criteria():
    """Render SEPA Criteria Analysis (box plots, super-performers)."""
    st.markdown("### SEPA Criteria Analysis")
    st.markdown("**S**eparation, **E**xplosiveness, **P**ersistence, **A**symmetry - Box plots reveal variance hidden by mean charts.")

    eda_data = load_eda_dashboard()

    if eda_data is None:
        st.warning("EDA dashboard data not generated yet.")
        st.markdown("""
        **To generate:**
        ```bash
        python model_runner.py workflow --start 2020-01-01 --end 2023-12-31 --steps load eda
        ```
        """)
        return

    # Sub-tabs for SEPA components
    sepa_tab1, sepa_tab2, sepa_tab3 = st.tabs([
        "Decile Box Plots",
        "Industry Analysis",
        "Super-Performers"
    ])

    with sepa_tab1:
        _render_sepa_decile_boxes(eda_data)

    with sepa_tab2:
        _render_sepa_industry(eda_data)

    with sepa_tab3:
        _render_sepa_super_performers(eda_data)


def _render_sepa_decile_boxes(eda_data: dict):
    """Render ALL decile box plots in a grid layout (no feature selection needed).

    Performance optimization: Renders plots in batches to avoid browser overload.
    """
    st.markdown("### Decile Monotonicity Analysis")
    st.markdown("**Box plots** show return distribution per decile - revealing variance hidden by mean charts")

    decile_box_data = eda_data.get('decile_box_data', {})

    if not decile_box_data:
        st.info("Decile box plot data not available. Re-run EDA workflow to generate.")
        return

    features = list(decile_box_data.keys())
    st.caption(f"Total: {len(features)} features with decile analysis")

    # Add a "Show Top N" slider to reduce initial load time (only if >6 features)
    if len(features) > 6:
        max_features = min(len(features), 20)
        n_features = st.slider(
            "Number of features to display",
            min_value=4,
            max_value=len(features),
            value=max_features,
            step=2,
            help="Showing fewer features improves page load speed"
        )
        features_to_show = features[:n_features]
    else:
        # For small datasets, show all features without slider
        features_to_show = features

    # Render features in grid layout (2 columns)
    for i in range(0, len(features_to_show), 2):
        col1, col2 = st.columns(2)

        with col1:
            if i < len(features_to_show):
                _render_single_decile_box(features_to_show[i], decile_box_data[features_to_show[i]])

        with col2:
            if i + 1 < len(features_to_show):
                _render_single_decile_box(features_to_show[i + 1], decile_box_data[features_to_show[i + 1]])


def _render_single_decile_box(feature_name: str, box_arrays: dict):
    """Render a single decile box plot with optimized visual clarity.

    Fixes:
    - Points side-by-side (pointpos=-1.8) instead of overlaid
    - Reduced jitter (0.2) for tighter scatter
    - Strict outlier-only mode for datasets >1000 samples
    - Box lines render on top with higher opacity
    """
    fig = go.Figure()

    for decile_name in sorted(box_arrays.keys(), key=lambda x: int(x[1:])):
        returns = box_arrays[decile_name]
        decile_num = int(decile_name[1:])
        n_samples = len(returns)

        # Adaptive point rendering: outliers only if >1000 samples
        if n_samples > 1000:
            boxpoints_mode = 'outliers'
        else:
            boxpoints_mode = 'outliers'  # Always use outliers to avoid browser overload

        fig.add_trace(go.Box(
            y=returns,
            name=decile_name,
            boxpoints=boxpoints_mode,
            jitter=0.2,  # Tighter scatter (was 0.3)
            pointpos=-1.8,  # Shift points to the left
            marker=dict(
                color='#2ca02c' if decile_num == 10 else '#1f77b4',
                size=2,
                opacity=0.3,  # Lower opacity for points
                line=dict(width=0)
            ),
            line=dict(color='black', width=2),  # Thicker box lines for visibility
            fillcolor='rgba(255,255,255,0.8)',  # Semi-transparent box fill
            boxmean=True,
            opacity=0.9  # Box geometry on top
        ))

    fig.add_hline(y=0, line_dash="dash", line_color="red", line_width=2)

    fig.update_layout(
        title=f"<b>{feature_name}</b>",
        xaxis_title="Decile",
        yaxis_title="Return %",
        template='plotly_white',
        height=400,
        showlegend=False,
        margin=dict(l=40, r=40, t=40, b=40),
        yaxis=dict(
            range=[-30, 100],
            zeroline=True,
            zerolinewidth=2,
            zerolinecolor='red'
        )
    )

    st.plotly_chart(fig, use_container_width=True)

    # Summary metrics (compact)
    d1_returns = box_arrays.get('D1', [])
    d10_returns = box_arrays.get('D10', [])

    if d1_returns and d10_returns:
        spread = np.median(d10_returns) - np.median(d1_returns)
        st.caption(
            f"D1: {np.median(d1_returns):.1f}% | D10: {np.median(d10_returns):.1f}% | "
            f"Spread: {spread:+.1f}% | D10 Max: {np.max(d10_returns):.0f}%"
        )


def _render_sepa_industry(eda_data: dict):
    """Render per-industry box plots."""
    st.markdown("### Industry Performance Analysis")
    st.markdown("Return distribution by industry - categorical analysis (not monotonicity)")

    industry_box_data = eda_data.get('industry_box_data', [])

    if not industry_box_data:
        st.info("Industry box plot data not available. Re-run EDA workflow to generate.")
        return

    # Create industry box plot using RAW DATA
    fig = go.Figure()

    for ind in industry_box_data[:15]:  # Top 15 industries
        returns = ind['returns']
        fig.add_trace(go.Box(
            y=returns,
            name=ind['industry'][:20],  # Truncate long names
            boxpoints='outliers',
            marker=dict(
                color='#1f77b4',
                size=2,
                opacity=0.5
            ),
            line=dict(color='black', width=1),
            boxmean=True
        ))

    fig.add_hline(y=0, line_dash="dash", line_color="gray", opacity=0.5)

    fig.update_layout(
        title="Return Distribution by Industry (Top 15 by Frequency)",
        xaxis_title='Industry',
        yaxis_title='Return (%)',
        template='plotly_white',
        height=500,
        showlegend=False,
        xaxis_tickangle=-45
    )

    st.plotly_chart(fig, use_container_width=True)

    # Summary table
    st.markdown("#### Industry Statistics")
    summary_data = []
    for ind in industry_box_data:
        returns = ind['returns']
        summary_data.append({
            'Industry': ind['industry'],
            'Trades': ind['count'],
            'Median %': np.median(returns),
            'Mean %': np.mean(returns),
            'Win Rate %': (np.array(returns) > 0).mean() * 100,
            '>50% Return %': (np.array(returns) > 50).mean() * 100,
            'Std Dev': np.std(returns)
        })

    ind_df = pd.DataFrame(summary_data)
    st.dataframe(
        ind_df.style.format({
            'Median %': '{:.2f}',
            'Mean %': '{:.2f}',
            'Win Rate %': '{:.1f}',
            '>50% Return %': '{:.1f}',
            'Std Dev': '{:.1f}'
        }),
        use_container_width=True,
        hide_index=True
    )


def _render_sepa_super_performers(eda_data: dict):
    """Render super-performer histogram (all 10 deciles)."""
    st.markdown("### Super-Performer Analysis")
    st.markdown("**The Home-Run Hunter**: What are the odds of catching a 100%+ winner?")

    super_perf = eda_data.get('super_performer_analysis', {})

    if not super_perf:
        st.info("Super-performer analysis not available. Re-run EDA workflow to generate.")
        return

    # Show summary metrics for key deciles
    col1, col2, col3 = st.columns(3)

    decile_configs = [
        ('decile_1', 'D1 (Lowest RS)', col1),
        ('decile_5', 'D5 (Middle RS)', col2),
        ('decile_10', 'D10 (Highest RS)', col3)
    ]

    for decile_key, title, col in decile_configs:
        if decile_key not in super_perf:
            continue

        data = super_perf[decile_key]
        with col:
            st.markdown(f"#### {title}")
            st.metric("Home Runs (>100%)", f"{data['n_home_runs']} ({data['pct_home_runs']:.1f}%)")
            st.metric("Super-Performers (>50%)", f"{data['n_super_performers']} ({data['pct_super_performers']:.1f}%)")
            st.metric("Median Return", f"{data['median_return']:.1f}%")

    st.markdown("---")

    # Histogram comparison - ALL 10 DECILES
    st.markdown("#### Return Distribution by RS Decile (All 10)")

    fig = go.Figure()

    # Color gradient from red (D1) to green (D10)
    colors = px.colors.sample_colorscale("RdYlGn", [i/9 for i in range(10)])

    for decile_num in range(1, 11):
        decile_key = f'decile_{decile_num}'
        if decile_key not in super_perf:
            continue

        data = super_perf[decile_key]
        fig.add_trace(go.Bar(
            name=f'D{decile_num}',
            x=data['return_bins'],
            y=data['counts'],
            marker_color=colors[decile_num - 1],
            text=data['counts'],
            textposition='outside',
            hovertemplate=(
                f"<b>Decile {decile_num}</b><br>"
                f"Bin: %{{x}}<br>"
                f"Count: %{{y}}<br>"
                f"Home Runs: {data['n_home_runs']} ({data['pct_home_runs']:.1f}%)<extra></extra>"
            )
        ))

    fig.update_layout(
        title="Trade Count by Return Bucket (Log Scale)",
        xaxis_title='Return Range',
        yaxis_title='Number of Trades',
        yaxis_type='log',
        barmode='group',
        template='plotly_white',
        height=500,
        legend=dict(
            orientation='v',
            yanchor='top',
            y=1,
            xanchor='right',
            x=1.15
        )
    )

    st.plotly_chart(fig, use_container_width=True)

    # Key insight
    if 'decile_10' in super_perf and 'decile_1' in super_perf:
        d10_hr = super_perf['decile_10']['pct_home_runs']
        d1_hr = super_perf['decile_1']['pct_home_runs']
        if d10_hr > 0 and d1_hr == 0:
            st.success(
                f"D10 has {d10_hr:.1f}% home runs vs D1's {d1_hr:.1f}%. "
                f"**Relative Strength is the gateway to Super-Performers.**"
            )
        elif d10_hr > d1_hr:
            st.info(f"D10 has {d10_hr:.1f}% home runs vs D1's {d1_hr:.1f}%")


def _render_d2_feature_analysis():
    """Render D2 Feature Analysis (feature leaderboard, KS, IC stability)."""
    st.markdown("### D2 Feature Analysis")
    st.markdown("Feature evaluation results from the Quant-Standard 4-Pillar pipeline.")

    eda_data = load_eda_dashboard()

    if eda_data is None:
        st.warning("EDA dashboard data not generated yet.")
        return

    # Metadata
    metadata = eda_data.get('metadata', {})
    st.caption(f"Generated: {metadata.get('generated_at', 'N/A')} | "
               f"Passed: {metadata.get('n_passed', 0)} | Failed: {metadata.get('n_failed', 0)}")

    # Summary metrics
    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.metric("Features Passed", metadata.get('n_passed', 0))
    with col2:
        st.metric("Features Failed", metadata.get('n_failed', 0))
    with col3:
        dataset_stats = eda_data.get('dataset_stats', {})
        st.metric("Total Samples", f"{dataset_stats.get('n_samples', 0):,}")
    with col4:
        st.metric("Win Rate", f"{dataset_stats.get('pct_positive', 0):.1f}%")

    st.markdown("---")

    # Sub-tabs
    feature_tab1, feature_tab2, feature_tab3 = st.tabs([
        "Feature Leaderboard",
        "KS Distributions",
        "IC Stability"
    ])

    with feature_tab1:
        _render_feature_leaderboard(eda_data)

    with feature_tab2:
        _render_ks_distributions(eda_data)

    with feature_tab3:
        _render_ic_stability(eda_data)


def _render_feature_leaderboard(eda_data: dict):
    """Render feature leaderboard."""
    st.markdown("### Feature Leaderboard")
    st.markdown("Features ranked by composite score (40% IC + 30% Stability + 30% KS)")

    feature_scores = eda_data.get('feature_scores', [])
    if feature_scores:
        df = pd.DataFrame(feature_scores)

        # Filter controls
        col1, col2 = st.columns([1, 3])
        with col1:
            show_filter = st.selectbox(
                "Show:",
                ["All", "Passed Only", "Failed Only"],
                key='d2_filter'
            )

        if show_filter == "Passed Only":
            df = df[df['passed'] == True]
        elif show_filter == "Failed Only":
            df = df[df['passed'] == False]

        # Format and display
        display_df = df[['feature', 'composite', 'ic_score', 'stability_score', 'ks_score', 'signal_type', 'passed']].copy()
        display_df.columns = ['Feature', 'Composite', 'IC', 'Stability', 'KS', 'Signal Type', 'Passed']

        # Color code
        def highlight_passed(row):
            if row['Passed']:
                return ['background-color: #d4edda'] * len(row)
            return ['background-color: #f8d7da'] * len(row)

        st.dataframe(
            display_df.style.apply(highlight_passed, axis=1).format({
                'Composite': '{:.3f}',
                'IC': '{:.3f}',
                'Stability': '{:.3f}',
                'KS': '{:.3f}'
            }),
            use_container_width=True,
            height=500
        )
    else:
        st.info("No feature scores available")


def _render_ks_distributions(eda_data: dict):
    """Render KS distribution comparisons."""
    st.markdown("### KS Distribution Comparison")
    st.markdown("Compare feature distributions between Q1 (losers) and Q4 (winners)")

    ks_distributions = eda_data.get('ks_distributions', {})
    if ks_distributions:
        features = list(ks_distributions.keys())
        selected_feature = st.selectbox("Select Feature:", features, key='d2_ks_feature')

        if selected_feature and selected_feature in ks_distributions:
            dist_data = ks_distributions[selected_feature]
            q1_values = dist_data.get('q1', [])
            q4_values = dist_data.get('q4', [])

            if q1_values and q4_values:
                fig = go.Figure()

                fig.add_trace(go.Histogram(
                    x=q1_values,
                    name='Q1 (Losers)',
                    marker_color='rgba(239, 83, 80, 0.6)',
                    nbinsx=30
                ))

                fig.add_trace(go.Histogram(
                    x=q4_values,
                    name='Q4 (Winners)',
                    marker_color='rgba(38, 166, 154, 0.6)',
                    nbinsx=30
                ))

                fig.add_vline(
                    x=dist_data.get('q1_median', 0),
                    line_dash="dash",
                    line_color="red",
                    annotation_text=f"Q1 Median: {dist_data.get('q1_median', 0):.2f}"
                )
                fig.add_vline(
                    x=dist_data.get('q4_median', 0),
                    line_dash="dash",
                    line_color="green",
                    annotation_text=f"Q4 Median: {dist_data.get('q4_median', 0):.2f}"
                )

                fig.update_layout(
                    title=f"KS Distribution: {selected_feature}",
                    barmode='overlay',
                    xaxis_title=selected_feature,
                    yaxis_title='Count',
                    template='plotly_white',
                    height=400
                )

                st.plotly_chart(fig, use_container_width=True)

                q1_med = dist_data.get('q1_median', 0)
                q4_med = dist_data.get('q4_median', 0)
                separation = abs(q4_med - q1_med)
                st.metric("Median Separation", f"{separation:.3f}")
    else:
        st.info("KS distribution data not available.")


def _render_ic_stability(eda_data: dict):
    """Render IC temporal stability."""
    st.markdown("### IC Temporal Stability")
    st.markdown("Information Coefficient consistency across years")

    ic_time_series = eda_data.get('ic_time_series', {})
    if ic_time_series:
        features = list(ic_time_series.keys())
        selected_features = st.multiselect(
            "Select Features (max 5):",
            features,
            default=features[:3] if len(features) >= 3 else features,
            max_selections=5,
            key='d2_ic_features'
        )

        if selected_features:
            fig = go.Figure()

            for feature in selected_features:
                ic_data = ic_time_series[feature]
                yearly_ics = ic_data.get('yearly_ics', {})

                if yearly_ics:
                    years = sorted(yearly_ics.keys())
                    values = [yearly_ics[y] for y in years]

                    fig.add_trace(go.Scatter(
                        x=years,
                        y=values,
                        name=feature,
                        mode='lines+markers'
                    ))

            fig.add_hline(y=0, line_dash="dash", line_color="gray")

            fig.update_layout(
                title="IC Time Series by Year",
                xaxis_title='Year',
                yaxis_title='Information Coefficient',
                template='plotly_white',
                height=400
            )

            st.plotly_chart(fig, use_container_width=True)
    else:
        st.info("IC time series data not available.")


def _render_candidate_profile():
    """Render Candidate Profile analysis."""
    st.markdown("### Candidate Profile Analysis")
    st.markdown("*Who are we trading? Are our filters correct?*")

    eda_data = load_eda_dashboard()

    if eda_data is None:
        st.warning("EDA dashboard data not generated yet.")
        return

    has_profile_data = eda_data and any(k in eda_data for k in ['filter_sensitivity', 'sector_efficiency', 'fundamental_sanity'])

    if not has_profile_data:
        st.info("""
        **Candidate Profile** data not yet generated.

        To generate, run the EDA workflow:
        ```bash
        python model_runner.py workflow --start 2020-01-01 --end 2023-12-31 --steps load eda select
        ```
        """)
        return

    # Sub-tabs
    profile_tab1, profile_tab2, profile_tab3 = st.tabs([
        "Filter Sensitivity",
        "Sector/Industry Efficiency",
        "Fundamental Sanity"
    ])

    with profile_tab1:
        if 'filter_sensitivity' in eda_data and eda_data['filter_sensitivity']:
            _render_filter_sensitivity(eda_data['filter_sensitivity'])

    with profile_tab2:
        if 'sector_efficiency' in eda_data and eda_data['sector_efficiency']:
            _render_sector_efficiency(
                eda_data['sector_efficiency'],
                eda_data.get('industry_efficiency', [])
            )

    with profile_tab3:
        if 'fundamental_sanity' in eda_data and eda_data['fundamental_sanity']:
            _render_fundamental_sanity(eda_data['fundamental_sanity'])


# =============================================================================
# PAGE 1: D1 ANALYSIS (Load pre-generated stats)
# =============================================================================

def render_d1_analysis():
    """Render D1 Analysis page - Trade Physics (from pre-generated report)."""
    from src.viz_library import (
        create_mae_mfe_scatter,
        create_e_ratio_histogram,
        create_time_to_peak_histogram
    )

    st.title("📊 D1 Analysis: Trade Physics")
    st.markdown("Trade characteristics: MAE/MFE, E-Ratio, crash rates.")

    # Try to load pre-generated report
    d1_report = load_d1_report()

    if d1_report is None:
        st.warning("D1 Analysis report not generated yet.")
        st.markdown("""
        **To generate:**
        ```bash
        python model.py m01 --steps train --report
        ```

        This will pre-compute trade physics and save to `models/d1_analysis.json`.
        """)

        # Fallback: show what the report WILL contain
        st.info("Once generated, this page will show:")
        col1, col2, col3, col4 = st.columns(4)
        with col1:
            st.metric("Total Trades", "N/A")
        with col2:
            st.metric("Median MFE", "N/A")
        with col3:
            st.metric("Median MAE", "N/A")
        with col4:
            st.metric("Crash Rate", "N/A")
        return

    # Display pre-computed metrics
    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.metric("Total Trades", f"{d1_report.get('total_trades', 0):,}")
    with col2:
        st.metric("Median MFE", f"{d1_report.get('median_mfe', 0):.1f}%")
    with col3:
        st.metric("Median MAE", f"{d1_report.get('median_mae', 0):.1f}%")
    with col4:
        st.metric("Median E-Ratio", f"{d1_report.get('median_e_ratio', 0):.2f}")

    # Crash rate from report
    st.markdown("### Crash Rate Analysis")
    crash_rate = d1_report.get('crash_rate', 0)
    survived_rate = 100 - crash_rate

    col1, col2 = st.columns(2)
    with col1:
        st.metric("Crashed", f"{crash_rate:.1f}%", delta=None)
    with col2:
        st.metric("Survived", f"{survived_rate:.1f}%", delta=None)

    st.info(f"Using stop multiplier: {d1_report.get('stop_multiplier', 2.0)}x nATR")

    # NEW: MAE/MFE Scatter Plot
    if 'mae_mfe_scatter' in d1_report and len(d1_report['mae_mfe_scatter']) > 0:
        st.markdown("---")
        st.markdown("### MAE/MFE Analysis")
        st.markdown("Maximum Adverse/Favorable Excursion scatter with E-Ratio reference lines. "
                   "Trades above the **E-Ratio 3.0** line indicate strong edge.")

        try:
            fig = create_mae_mfe_scatter(d1_report['mae_mfe_scatter'])
            st.plotly_chart(fig, use_container_width=True)
        except Exception as e:
            st.error(f"Error rendering MAE/MFE scatter: {e}")

    # NEW: E-Ratio Distribution
    if 'e_ratio_distribution' in d1_report and len(d1_report['e_ratio_distribution']) > 0:
        st.markdown("---")
        st.markdown("### E-Ratio Distribution")
        pct_above = d1_report.get('e_ratio_gt_3_pct', 0)
        st.markdown(f"E-Ratio = MFE / |MAE| measures upside/downside asymmetry. "
                   f"**{pct_above:.1f}%** of trades exceed the 3.0 benchmark.")

        try:
            fig = create_e_ratio_histogram(d1_report['e_ratio_distribution'], benchmark=3.0)
            st.plotly_chart(fig, use_container_width=True)
        except Exception as e:
            st.error(f"Error rendering E-Ratio histogram: {e}")

    # NEW: Time to Peak
    if 'time_to_peak' in d1_report and len(d1_report['time_to_peak']) > 0:
        st.markdown("---")
        st.markdown("### Time to Peak (MFE)")
        median_days = pd.Series(d1_report['time_to_peak']).median()
        st.markdown(f"Days to reach Maximum Favorable Excursion. "
                   f"Median: **{median_days:.0f} days**. This informs optimal holding periods.")

        try:
            fig = create_time_to_peak_histogram(d1_report['time_to_peak'])
            st.plotly_chart(fig, use_container_width=True)
        except Exception as e:
            st.error(f"Error rendering time-to-peak histogram: {e}")

    # ==========================================================================
    # CANDIDATE PROFILE ANALYSIS (Phase 1: D1/D2)
    # ==========================================================================
    st.markdown("---")
    st.markdown("## Candidate Profile Analysis")
    st.markdown("*Who are we trading? Are our filters correct?*")

    # Load candidate profile from EDA dashboard JSON (generated by workflow --steps eda)
    eda_data = load_eda_dashboard()

    # Check if candidate profile data exists in EDA data
    has_profile_data = eda_data and any(k in eda_data for k in ['filter_sensitivity', 'sector_efficiency', 'fundamental_sanity'])

    if not has_profile_data:
        st.info("""
        **Candidate Profile** data not yet generated.

        To generate, run the EDA workflow:
        ```bash
        python model_runner.py workflow --start 2020-01-01 --end 2023-12-31 --steps load eda select
        ```

        This will compute:
        - Filter Sensitivity (RS threshold yield curve)
        - Sector/Industry Efficiency (freq vs return)
        - Fundamental Sanity Check (price/mktCap distributions)
        """)
    else:
        # --- 1. Filter Sensitivity (RS Threshold Yield Curve) ---
        if 'filter_sensitivity' in eda_data and eda_data['filter_sensitivity']:
            _render_filter_sensitivity(eda_data['filter_sensitivity'])

        # --- 2. Sector/Industry Efficiency ---
        if 'sector_efficiency' in eda_data and eda_data['sector_efficiency']:
            _render_sector_efficiency(
                eda_data['sector_efficiency'],
                eda_data.get('industry_efficiency', [])
            )

        # --- 3. Fundamental Sanity Check ---
        if 'fundamental_sanity' in eda_data and eda_data['fundamental_sanity']:
            _render_fundamental_sanity(eda_data['fundamental_sanity'])


def _render_filter_sensitivity(filter_data: list):
    """Render the RS threshold yield curve."""
    st.markdown("### Filter Sensitivity (RS Threshold)")
    st.markdown(
        "The **Yield Curve** shows how tightening the RS filter affects candidate count vs win rate. "
        "Look for the *knee* where win rate improves without losing too many candidates."
    )

    df = pd.DataFrame(filter_data)

    # Dual-axis chart
    fig = go.Figure()

    # Candidate count (bars)
    fig.add_trace(go.Bar(
        x=df['threshold'],
        y=df['candidate_count'],
        name='Candidates',
        yaxis='y',
        marker_color='rgba(55, 83, 109, 0.7)',
        text=df['candidate_count'],
        textposition='outside'
    ))

    # Win rate (line)
    fig.add_trace(go.Scatter(
        x=df['threshold'],
        y=df['win_rate'],
        name='Win Rate %',
        yaxis='y2',
        mode='lines+markers',
        line=dict(color='#2ca02c', width=3),
        marker=dict(size=10)
    ))

    # Average return (line)
    fig.add_trace(go.Scatter(
        x=df['threshold'],
        y=df['avg_return'],
        name='Avg Return %',
        yaxis='y2',
        mode='lines+markers',
        line=dict(color='#d62728', width=2, dash='dash'),
        marker=dict(size=8)
    ))

    fig.update_layout(
        title='RS Threshold Sensitivity Analysis',
        xaxis=dict(title='RS Rating Threshold', tickmode='array', tickvals=df['threshold']),
        yaxis=dict(title='Candidate Count', side='left'),
        yaxis2=dict(title='Win Rate / Avg Return %', overlaying='y', side='right'),
        legend=dict(orientation='h', yanchor='bottom', y=1.02),
        height=400
    )

    st.plotly_chart(fig, use_container_width=True)

    # Data table
    with st.expander("View Raw Data"):
        st.dataframe(df, use_container_width=True, hide_index=True)


def _render_sector_efficiency(sector_data: list, industry_data: list):
    """Render sector/industry efficiency scatter plots."""
    st.markdown("### Sector/Industry Efficiency")
    st.markdown(
        "**Frequency vs Potential**: Top-right = bread & butter (trade often, good MFE). "
        "Bottom-right = kill zone (trade often, poor results). Consider blacklisting."
    )

    tab1, tab2 = st.tabs(["Sectors", "Industries"])

    with tab1:
        if sector_data:
            df = pd.DataFrame(sector_data)

            fig = px.scatter(
                df,
                x='freq_pct',
                y='avg_return',
                size='count',
                color='win_rate',
                color_continuous_scale='RdYlGn',
                hover_name='sector',
                hover_data={'freq_pct': ':.1f', 'avg_return': ':.2f', 'win_rate': ':.1f', 'count': True},
                labels={
                    'freq_pct': '% of Trades (Frequency)',
                    'avg_return': 'Avg Return %',
                    'win_rate': 'Win Rate %'
                }
            )

            # Add quadrant lines
            fig.add_hline(y=0, line_dash="dash", line_color="gray", opacity=0.5)
            fig.add_vline(x=df['freq_pct'].median(), line_dash="dash", line_color="gray", opacity=0.5)

            # Add text labels
            for _, row in df.iterrows():
                fig.add_annotation(
                    x=row['freq_pct'],
                    y=row['avg_return'],
                    text=row['sector'][:10],
                    showarrow=False,
                    yshift=15,
                    font=dict(size=9)
                )

            fig.update_layout(
                title='Sector Efficiency Map',
                height=450,
                coloraxis_colorbar=dict(title='Win Rate %')
            )

            st.plotly_chart(fig, use_container_width=True)

            # Summary table
            st.dataframe(
                df[['sector', 'count', 'freq_pct', 'avg_return', 'win_rate']].sort_values('count', ascending=False),
                use_container_width=True,
                hide_index=True
            )

    with tab2:
        if industry_data:
            df = pd.DataFrame(industry_data)

            fig = px.scatter(
                df,
                x='freq_pct',
                y='avg_return',
                size='count',
                color='win_rate',
                color_continuous_scale='RdYlGn',
                hover_name='industry',
                hover_data={'freq_pct': ':.1f', 'avg_return': ':.2f', 'win_rate': ':.1f', 'count': True},
                labels={
                    'freq_pct': '% of Trades (Frequency)',
                    'avg_return': 'Avg Return %',
                    'win_rate': 'Win Rate %'
                }
            )

            fig.add_hline(y=0, line_dash="dash", line_color="gray", opacity=0.5)
            fig.update_layout(
                title='Top 20 Industries Efficiency',
                height=450,
                coloraxis_colorbar=dict(title='Win Rate %')
            )

            st.plotly_chart(fig, use_container_width=True)

            st.dataframe(
                df[['industry', 'count', 'freq_pct', 'avg_return', 'win_rate']].sort_values('count', ascending=False),
                use_container_width=True,
                hide_index=True
            )


def _render_fundamental_sanity(sanity_data: dict):
    """Render fundamental sanity check histograms."""
    st.markdown("### Fundamental Sanity Check")
    st.markdown(
        "Distribution of Price, Market Cap, and Beta. "
        "Check if we're accidentally trading illiquid micro-caps or penny stocks."
    )

    col1, col2, col3 = st.columns(3)

    # Price distribution
    with col1:
        if 'price_distribution' in sanity_data:
            pd_stats = sanity_data['price_distribution']
            st.metric("Median Price", f"${pd_stats['median']:.2f}")
            st.metric("% Under $5", f"{pd_stats['pct_under_5']:.1f}%",
                     delta=None if pd_stats['pct_under_5'] < 5 else "High Risk",
                     delta_color="inverse")
            st.metric("% Under $10", f"{pd_stats['pct_under_10']:.1f}%")

            if 'histogram' in pd_stats:
                hist_df = pd.DataFrame(pd_stats['histogram'])
                fig = px.bar(hist_df, x='label', y='count', title='Price Distribution')
                fig.update_layout(height=250, showlegend=False)
                st.plotly_chart(fig, use_container_width=True)

    # Market Cap distribution
    with col2:
        if 'mktcap_distribution' in sanity_data:
            mc_stats = sanity_data['mktcap_distribution']
            st.metric("Median MktCap", f"${mc_stats['median_b']:.1f}B")
            st.metric("% Micro (<$300M)", f"{mc_stats['pct_micro']:.1f}%",
                     delta=None if mc_stats['pct_micro'] < 20 else "Caution",
                     delta_color="inverse")
            st.metric("% Large (>$10B)", f"{mc_stats['pct_large']:.1f}%")

            # Pie chart for cap breakdown
            cap_data = {
                'Micro (<$300M)': mc_stats['pct_micro'],
                'Small ($300M-$2B)': mc_stats['pct_small'],
                'Mid ($2B-$10B)': mc_stats['pct_mid'],
                'Large (>$10B)': mc_stats['pct_large']
            }
            fig = px.pie(
                values=list(cap_data.values()),
                names=list(cap_data.keys()),
                title='Market Cap Breakdown'
            )
            fig.update_layout(height=250, showlegend=True)
            st.plotly_chart(fig, use_container_width=True)

    # Beta distribution
    with col3:
        if 'beta_distribution' in sanity_data:
            beta_stats = sanity_data['beta_distribution']
            st.metric("Median Beta", f"{beta_stats['median']:.2f}")
            st.metric("% Low Beta (<0.8)", f"{beta_stats['pct_low']:.1f}%")
            st.metric("% High Beta (>1.2)", f"{beta_stats['pct_high']:.1f}%")

            # Beta breakdown
            beta_data = {
                'Low (<0.8)': beta_stats['pct_low'],
                'Normal (0.8-1.2)': beta_stats['pct_normal'],
                'High (>1.2)': beta_stats['pct_high']
            }
            fig = px.pie(
                values=list(beta_data.values()),
                names=list(beta_data.keys()),
                title='Beta Breakdown'
            )
            fig.update_layout(height=250, showlegend=True)
            st.plotly_chart(fig, use_container_width=True)


# =============================================================================
# PAGE 2: M01 REPORT (Load config JSON)
# =============================================================================

def render_m01_report():
    """Render M01 Report page - loads pre-generated model config."""
    from src.viz_library import (
        create_decile_bar_chart,
        create_actual_vs_predicted_scatter,
        create_feature_importance_waterfall,
        create_residual_plot
    )

    st.title("📈 M01 Report: Return Regressor")
    st.markdown("Walk-forward validation results and feature importance.")

    # Model version selector
    available_versions = discover_model_versions('m01')
    
    if not available_versions:
        st.warning("No M01 models trained yet.")
        st.markdown("""
        **To train and generate report:**
        ```bash
        python model_runner.py m01 --steps train --report
        ```
        """)
        return
    
    # Format display names (e.g., 'm01' -> 'M01', 'm01_v2' -> 'M01_V2')
    display_names = {v: v.upper() for v in available_versions}
    
    selected_model = st.selectbox(
        "Select Model Version",
        options=available_versions,
        format_func=lambda x: display_names[x],
        help="Compare different model versions trained with different feature sets"
    )

    # Load from pre-generated config
    config = load_model_config(selected_model)
    importance_df = load_feature_importance(selected_model)

    if config is None:
        st.warning(f"{selected_model.upper()} model config not found.")
        return

    # Model metadata
    st.markdown("### Model Information")
    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.metric("Model", config.get('model_name', selected_model).upper())
    with col2:
        st.metric("Model Type", config.get('model_type', 'N/A').upper())
    with col3:
        st.metric("Features", len(config.get('feature_columns', [])))
    with col4:
        created = config.get('created_at', 'N/A')[:10] if config.get('created_at') else 'N/A'
        st.metric("Created", created)

    # Walk-forward results from config
    metrics = config.get('validation_metrics', [])
    if metrics:
        st.markdown("### Walk-Forward Validation Results")

        metrics_df = pd.DataFrame(metrics)

        # Summary stats
        avg_edge = metrics_df['selection_edge'].mean()
        avg_rmse = metrics_df['rmse'].mean()
        positive_folds = (metrics_df['selection_edge'] > 0).sum()
        avg_top = metrics_df['top_decile_mean'].mean()

        col1, col2, col3, col4 = st.columns(4)
        with col1:
            st.metric("Avg Edge", f"{avg_edge:+.2f}%")
        with col2:
            st.metric("Avg RMSE", f"{avg_rmse:.2f}%")
        with col3:
            st.metric("Positive Folds", f"{positive_folds}/{len(metrics_df)}")
        with col4:
            st.metric("Top Decile", f"{avg_top:.2f}%")

        # Table
        st.dataframe(
            metrics_df[['test_year', 'test_samples', 'rmse', 'selection_edge', 'top_decile_mean']].round(2),
            use_container_width=True,
            hide_index=True
        )

        # Edge bar chart
        st.markdown("### Selection Edge Over Time")
        fig = px.bar(
            metrics_df,
            x='test_year',
            y='selection_edge',
            title='Selection Edge by Test Year',
            color='selection_edge',
            color_continuous_scale=['red', 'yellow', 'green'],
            color_continuous_midpoint=0
        )
        fig.add_hline(y=0, line_dash="dash", line_color="gray")
        fig.update_layout(height=350, template='plotly_white')
        st.plotly_chart(fig, use_container_width=True)

    # NEW: Decile Performance Analysis
    if 'decile_performance' in config and len(config['decile_performance']) > 0:
        st.markdown("---")
        st.markdown("### Decile Performance Analysis")
        st.markdown("Mean return % by predicted return decile. Decile 1 = highest predicted returns.")

        try:
            fig = create_decile_bar_chart(config['decile_performance'])
            st.plotly_chart(fig, use_container_width=True)
        except Exception as e:
            st.error(f"Error rendering decile chart: {e}")

    # NEW: Actual vs Predicted Scatter
    if 'predictions_sample' in config and len(config['predictions_sample']) > 0:
        st.markdown("---")
        st.markdown("### Actual vs Predicted Returns")
        st.markdown("Scatter plot of model predictions vs actual outcomes. Points near the diagonal line indicate accurate predictions.")

        try:
            fig = create_actual_vs_predicted_scatter(config['predictions_sample'])
            st.plotly_chart(fig, use_container_width=True)
        except Exception as e:
            st.error(f"Error rendering scatter plot: {e}")

        # NEW: Residual Analysis
        st.markdown("---")
        st.markdown("### Residual Analysis")
        st.markdown("Residuals (actual - predicted) should be randomly distributed around zero with no patterns.")

        try:
            fig = create_residual_plot(config['predictions_sample'])
            st.plotly_chart(fig, use_container_width=True)
        except Exception as e:
            st.error(f"Error rendering residual plot: {e}")

    # NEW: Error Analysis (FOMO vs Toxic)
    if 'error_analysis' in config:
        st.markdown("---")
        st.markdown("### Error Analysis: FOMO vs Toxic")
        st.markdown("**FOMO**: Predicted low, but actual high (missed winners). "
                   "**Toxic**: Predicted high, but actual low (false positives).")

        err = config['error_analysis']
        col1, col2, col3, col4 = st.columns(4)

        with col1:
            st.metric("FOMO Errors", err.get('FOMO', {}).get('count', 0),
                     delta=f"{err.get('FOMO', {}).get('avg_missed_return', 0):.1f}% missed")
        with col2:
            st.metric("Toxic Errors", err.get('Toxic', {}).get('count', 0),
                     delta=f"{err.get('Toxic', {}).get('avg_loss', 0):.1f}% avg")
        with col3:
            st.metric("True Positives", err.get('True_Positive', {}).get('count', 0),
                     delta=f"{err.get('True_Positive', {}).get('avg_return', 0):.1f}% avg")
        with col4:
            st.metric("True Negatives", err.get('True_Negative', {}).get('count', 0),
                     delta=f"{err.get('True_Negative', {}).get('avg_return', 0):.1f}% avg")

    # Feature importance (from CSV) - Enhanced with Waterfall
    if importance_df is not None and len(importance_df) > 0:
        st.markdown("---")
        st.markdown("### Feature Importance")

        top_n = st.slider("Show top N features", 10, 30, 20)

        try:
            fig = create_feature_importance_waterfall(importance_df, top_n=top_n)
            st.plotly_chart(fig, use_container_width=True)
        except Exception as e:
            st.error(f"Error rendering waterfall chart: {e}")


# =============================================================================
# PAGE 3: M02 REPORT (Load config JSON)
# =============================================================================

def render_m02_report():
    """Render M02 Report page - loads pre-generated model config."""
    st.title("🎯 M02 Report: Ignition Classifier")
    st.markdown("Triple barrier classification results.")
    
    config = load_model_config('m02')
    d3_summary = load_d3_summary()
    
    # D3 Summary (pre-computed)
    if d3_summary:
        st.markdown("### Triple Barrier Outcomes")
        
        col1, col2, col3 = st.columns(3)
        with col1:
            tp = d3_summary.get('tp_rate', 0)
            st.metric("Take Profit", f"{tp:.1f}%")
        with col2:
            sl = d3_summary.get('sl_rate', 0)
            st.metric("Stop Loss", f"{sl:.1f}%")
        with col3:
            time_exit = d3_summary.get('time_rate', 0)
            st.metric("Time Exit", f"{time_exit:.1f}%")
        
        # Pie chart
        fig = px.pie(
            values=[tp, sl, time_exit],
            names=['TP', 'SL', 'Time'],
            title='Barrier Outcome Distribution',
            color_discrete_sequence=['green', 'red', 'gray']
        )
        fig.update_layout(height=350)
        st.plotly_chart(fig, use_container_width=True)
    else:
        st.info("D3 summary not found. Run `python model.py m02 --steps label` first.")
    
    # Model metrics from config
    if config:
        st.markdown("### Model Validation Results")
        
        metrics = config.get('validation_metrics', [])
        if metrics:
            metrics_df = pd.DataFrame(metrics)
            
            if 'auc' in metrics_df.columns:
                avg_auc = metrics_df['auc'].mean()
                st.metric("Average AUC", f"{avg_auc:.3f}")
            
            st.dataframe(metrics_df, use_container_width=True, hide_index=True)
    else:
        st.warning("M02 model not trained. Run `python model.py m02 --steps train` first.")


# =============================================================================
# PAGE 4: DUAL-MODEL ANALYSIS
# =============================================================================

def render_dual_model():
    """Render Dual-Model page - Combined M01+M02 analysis."""
    st.title("🔀 Dual-Model Analysis")
    st.markdown("Compare M01 (regression) and M02 (classification) model outputs.")
    
    m01_config = load_model_config('m01')
    m02_config = load_model_config('m02')
    
    col1, col2 = st.columns(2)
    
    with col1:
        st.markdown("### M01 (Regressor)")
        if m01_config:
            metrics = m01_config.get('validation_metrics', [])
            if metrics:
                avg_edge = np.mean([m['selection_edge'] for m in metrics])
                st.metric("Selection Edge", f"{avg_edge:+.2f}%")
                st.metric("Features", len(m01_config.get('feature_columns', [])))
        else:
            st.info("M01 not trained")
    
    with col2:
        st.markdown("### M02 (Classifier)")
        if m02_config:
            metrics = m02_config.get('validation_metrics', [])
            if metrics and 'auc' in metrics[0]:
                avg_auc = np.mean([m['auc'] for m in metrics])
                st.metric("Average AUC", f"{avg_auc:.3f}")
            st.metric("Features", len(m02_config.get('feature_columns', [])))
        else:
            st.info("M02 not trained")
    
    st.markdown("---")
    st.markdown("""
    ### Combined Scoring Strategy
    
    **Dual-Model Approach:**
    1. M01 predicts expected return %
    2. M02 predicts ignition probability
    3. Combined rank uses both signals
    
    **Filter:** M01 Rank ≤ 3 AND M02 Prob > 0.5
    """)


# =============================================================================
# PAGE 5: BACKTEST (Interactive Analytics)
# =============================================================================

BACKTEST_RUNS_DIR = Path('data/backtest/runs')


@st.cache_data(ttl=600)  # Backtest runs don't change often (10 min cache)
def discover_backtest_runs() -> list:
    """Scan data/backtest/runs/ for available backtest runs."""
    if not BACKTEST_RUNS_DIR.exists():
        return []

    runs = []
    for run_dir in BACKTEST_RUNS_DIR.iterdir():
        if run_dir.is_dir():
            manifest_path = run_dir / 'manifest.json'
            if manifest_path.exists():
                runs.append(run_dir.name)

    # Sort by name (newest first since names include date)
    return sorted(runs, reverse=True)


@st.cache_data(ttl=600)
def load_backtest_manifest(run_id: str) -> dict:
    """Load manifest.json for a backtest run."""
    manifest_path = BACKTEST_RUNS_DIR / run_id / 'manifest.json'
    if manifest_path.exists():
        with open(manifest_path, 'r') as f:
            return json.load(f)
    return {}


@st.cache_data(ttl=600)
def load_backtest_metrics(run_id: str) -> dict:
    """Load metrics.json for a backtest run."""
    metrics_path = BACKTEST_RUNS_DIR / run_id / 'metrics.json'
    if metrics_path.exists():
        with open(metrics_path, 'r') as f:
            return json.load(f)
    return {}


@st.cache_data(ttl=600)
def load_backtest_equity(run_id: str):
    """Load equity_curve.parquet for a backtest run.

    Performance: Parquet is fast, but cache to avoid repeated I/O.
    """
    equity_path = BACKTEST_RUNS_DIR / run_id / 'equity_curve.parquet'
    if equity_path.exists():
        return pd.read_parquet(equity_path)
    return None


@st.cache_data(ttl=600)
def load_backtest_trades(run_id: str):
    """Load trades.parquet for a backtest run.

    Performance: Can be large (>10k rows), cache aggressively.
    """
    trades_path = BACKTEST_RUNS_DIR / run_id / 'trades.parquet'
    if trades_path.exists():
        return pd.read_parquet(trades_path)
    return None


def format_run_label(run_id: str) -> str:
    """Format run ID for dropdown display."""
    manifest = load_backtest_manifest(run_id)
    if not manifest:
        return run_id

    # Extract key info
    created = manifest.get('created_at', '')[:10]
    summary = manifest.get('summary_metrics', {})
    ret = summary.get('total_return', 0)
    sharpe = summary.get('sharpe_ratio', 0)
    trades = summary.get('total_trades', 0)

    return f"{created} | {ret:+.0f}% | Sharpe {sharpe:.2f} | {trades} trades"


def render_backtest():
    """Render Backtest page with interactive charts from cached data."""
    from src.viz_library import (
        create_backtest_equity_curve,
        create_backtest_drawdown,
        create_backtest_monthly_heatmap,
        create_backtest_trade_histogram,
        create_backtest_regime_bars,
        create_backtest_exit_pie,
        create_backtest_holding_days_histogram,
        create_backtest_cash_overlay,
    )

    st.title("📊 Backtest Results")

    # Discover available runs
    runs = discover_backtest_runs()

    if not runs:
        st.warning("No backtest runs found.")
        st.markdown("""
        **To generate:**
        ```bash
        python scripts/run_backtest.py --run
        ```

        This will run a backtest and save results to `data/backtest/runs/`.
        """)
        return

    # Run selector dropdown
    selected_run = st.selectbox(
        "Select Backtest Run",
        options=runs,
        format_func=format_run_label,
        help="Select a backtest run to view results"
    )

    # Load data
    manifest = load_backtest_manifest(selected_run)
    metrics = load_backtest_metrics(selected_run)
    equity_df = load_backtest_equity(selected_run)
    trade_df = load_backtest_trades(selected_run)

    if not manifest:
        st.error(f"Failed to load manifest for {selected_run}")
        return

    # Summary metrics cards
    st.markdown("### Performance Summary")
    summary = manifest.get('summary_metrics', {})

    col1, col2, col3, col4, col5 = st.columns(5)
    with col1:
        st.metric("Total Return", f"{summary.get('total_return', 0):+.1f}%")
    with col2:
        st.metric("Sharpe Ratio", f"{summary.get('sharpe_ratio', 0):.2f}")
    with col3:
        st.metric("Max Drawdown", f"{summary.get('max_drawdown', 0):.1f}%")
    with col4:
        st.metric("Win Rate", f"{summary.get('win_rate', 0):.1f}%")
    with col5:
        st.metric("Total Trades", summary.get('total_trades', 0))

    # Parameters expander
    with st.expander("📋 Backtest Parameters", expanded=False):
        params = manifest.get('params', {})
        col1, col2 = st.columns(2)
        with col1:
            st.markdown("**Date Range:**")
            st.write(f"Start: {params.get('start_date', 'N/A')}")
            st.write(f"End: {params.get('end_date', 'N/A')}")
            st.write(f"Initial Cash: ${params.get('initial_cash', 0):,.0f}")
        with col2:
            st.markdown("**Strategy Parameters:**")
            st.write(f"Min Score: {params.get('min_score', 'N/A')}")
            st.write(f"Min Percentile: {params.get('min_percentile', 'N/A')}")
            st.write(f"ATR Stop Mult: {params.get('atr_stop_mult', 'N/A')}")

    st.markdown("---")

    # Tabbed charts
    tab1, tab2, tab3, tab4, tab5, tab6 = st.tabs([
        "Equity Curve",
        "Monthly Returns",
        "Trade Analysis",
        "Regime Analysis",
        "Exit Analysis",
        "Holding Period"
    ])

    with tab1:
        st.markdown("### Equity Curve with Regime Overlay")
        if equity_df is not None and len(equity_df) > 0:
            try:
                fig = create_backtest_equity_curve(equity_df)
                st.plotly_chart(fig, use_container_width=True)

                # Cash overlay option
                if st.checkbox("Show Cash Overlay", value=False):
                    fig_cash = create_backtest_cash_overlay(equity_df)
                    st.plotly_chart(fig_cash, use_container_width=True)

                # Drawdown
                st.markdown("### Drawdown Analysis")
                fig_dd = create_backtest_drawdown(equity_df)
                st.plotly_chart(fig_dd, use_container_width=True)
            except Exception as e:
                st.error(f"Error rendering equity curve: {e}")
        else:
            st.info("Equity curve data not available")

    with tab2:
        st.markdown("### Monthly Returns Heatmap")
        monthly_returns = metrics.get('monthly_returns', [])
        if monthly_returns:
            try:
                fig = create_backtest_monthly_heatmap(monthly_returns)
                st.plotly_chart(fig, use_container_width=True)
            except Exception as e:
                st.error(f"Error rendering heatmap: {e}")
        else:
            st.info("Monthly returns data not available")

    with tab3:
        st.markdown("### Trade PnL Distribution")
        if trade_df is not None and len(trade_df) > 0:
            try:
                fig = create_backtest_trade_histogram(trade_df['pnl_percent'].tolist())
                st.plotly_chart(fig, use_container_width=True)

                # Trade stats
                st.markdown("### Trade Statistics")
                col1, col2, col3, col4 = st.columns(4)
                with col1:
                    st.metric("Avg Return", f"{trade_df['pnl_percent'].mean():.2f}%")
                with col2:
                    st.metric("Median Return", f"{trade_df['pnl_percent'].median():.2f}%")
                with col3:
                    st.metric("Best Trade", f"{trade_df['pnl_percent'].max():.2f}%")
                with col4:
                    st.metric("Worst Trade", f"{trade_df['pnl_percent'].min():.2f}%")
            except Exception as e:
                st.error(f"Error rendering trade analysis: {e}")
        else:
            st.info("Trade data not available")

    with tab4:
        st.markdown("### Performance by Entry Regime")
        regime_perf = metrics.get('regime_performance', [])
        if regime_perf:
            try:
                fig = create_backtest_regime_bars(regime_perf)
                st.plotly_chart(fig, use_container_width=True)
            except Exception as e:
                st.error(f"Error rendering regime analysis: {e}")
        else:
            st.info("Regime performance data not available")

    with tab5:
        st.markdown("### Exit Reason Breakdown")
        exit_reasons = metrics.get('exit_reasons', {})
        if exit_reasons:
            try:
                fig = create_backtest_exit_pie(exit_reasons)
                st.plotly_chart(fig, use_container_width=True)
            except Exception as e:
                st.error(f"Error rendering exit analysis: {e}")
        else:
            st.info("Exit reasons data not available")

    with tab6:
        st.markdown("### Holding Period Distribution")
        if trade_df is not None and 'holding_days' in trade_df.columns:
            try:
                fig = create_backtest_holding_days_histogram(trade_df['holding_days'].tolist())
                st.plotly_chart(fig, use_container_width=True)

                # Stats
                col1, col2, col3 = st.columns(3)
                with col1:
                    st.metric("Avg Days", f"{trade_df['holding_days'].mean():.1f}")
                with col2:
                    st.metric("Median Days", f"{trade_df['holding_days'].median():.0f}")
                with col3:
                    st.metric("Max Days", f"{trade_df['holding_days'].max():.0f}")
            except Exception as e:
                st.error(f"Error rendering holding period: {e}")
        else:
            st.info("Holding period data not available")

    # Legacy reports section
    st.markdown("---")
    with st.expander("📜 Legacy Markdown Reports", expanded=False):
        legacy_dir = Path('data/backtest/reports')
        if legacy_dir.exists():
            legacy_files = sorted(legacy_dir.glob('*.md'), reverse=True)
            if legacy_files:
                selected_legacy = st.selectbox(
                    "View legacy report",
                    options=legacy_files,
                    format_func=lambda x: x.name
                )
                if selected_legacy:
                    st.markdown(selected_legacy.read_text(encoding='utf-8'))
            else:
                st.info("No legacy markdown reports found")
        else:
            st.info("Legacy reports directory not found")


# =============================================================================
# PAGE: EDA FEATURE SCREENING (D2 Feature Analysis)
# =============================================================================

def render_eda_feature_screening():
    """Render EDA Feature Screening page - D2 Feature Analysis from pre-generated JSON."""
    st.title("📊 EDA Feature Screening")
    st.markdown("Feature evaluation results from the Quant-Standard 4-Pillar pipeline.")

    # Load pre-generated EDA dashboard data
    eda_data = load_eda_dashboard()

    if eda_data is None:
        st.warning("EDA dashboard data not generated yet.")
        st.markdown("""
        **To generate:**
        ```bash
        python model_runner.py workflow --start 2020-01-01 --end 2023-12-31 --steps eda
        ```

        This will create both:
        - `models/eda_report.md` (human-readable report)
        - `models/eda_dashboard.json` (dashboard visualization data)
        """)
        return

    # Metadata
    metadata = eda_data.get('metadata', {})
    st.caption(f"Generated: {metadata.get('generated_at', 'N/A')} | "
               f"Passed: {metadata.get('n_passed', 0)} | Failed: {metadata.get('n_failed', 0)}")

    # Summary metrics
    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.metric("Features Passed", metadata.get('n_passed', 0))
    with col2:
        st.metric("Features Failed", metadata.get('n_failed', 0))
    with col3:
        dataset_stats = eda_data.get('dataset_stats', {})
        st.metric("Total Samples", f"{dataset_stats.get('n_samples', 0):,}")
    with col4:
        st.metric("Win Rate", f"{dataset_stats.get('pct_positive', 0):.1f}%")

    st.markdown("---")

    # Tabs for different views (enhanced with SEPA analysis)
    tab1, tab2, tab3, tab4, tab5, tab6 = st.tabs([
        "Feature Leaderboard",
        "KS Distributions",
        "Decile Box Plots",
        "Industry Analysis",
        "Super-Performers",
        "IC Stability"
    ])

    # Tab 1: Feature Leaderboard
    with tab1:
        st.markdown("### Feature Leaderboard")
        st.markdown("Features ranked by composite score (40% IC + 30% Stability + 30% KS)")

        feature_scores = eda_data.get('feature_scores', [])
        if feature_scores:
            # Convert to DataFrame
            df = pd.DataFrame(feature_scores)

            # Filter controls
            col1, col2 = st.columns([1, 3])
            with col1:
                show_filter = st.selectbox(
                    "Show:",
                    ["All", "Passed Only", "Failed Only"]
                )

            if show_filter == "Passed Only":
                df = df[df['passed'] == True]
            elif show_filter == "Failed Only":
                df = df[df['passed'] == False]

            # Format and display
            display_df = df[['feature', 'composite', 'ic_score', 'stability_score', 'ks_score', 'signal_type', 'passed']].copy()
            display_df.columns = ['Feature', 'Composite', 'IC', 'Stability', 'KS', 'Signal Type', 'Passed']

            # Color code
            def highlight_passed(row):
                if row['Passed']:
                    return ['background-color: #d4edda'] * len(row)
                return ['background-color: #f8d7da'] * len(row)

            st.dataframe(
                display_df.style.apply(highlight_passed, axis=1).format({
                    'Composite': '{:.3f}',
                    'IC': '{:.3f}',
                    'Stability': '{:.3f}',
                    'KS': '{:.3f}'
                }),
                use_container_width=True,
                height=500
            )
        else:
            st.info("No feature scores available")

    # Tab 2: KS Distributions (Q1 vs Q4)
    with tab2:
        st.markdown("### KS Distribution Comparison")
        st.markdown("Compare feature distributions between Q1 (losers) and Q4 (winners)")

        ks_distributions = eda_data.get('ks_distributions', {})
        if ks_distributions:
            # Feature selector
            features = list(ks_distributions.keys())
            selected_feature = st.selectbox("Select Feature:", features)

            if selected_feature and selected_feature in ks_distributions:
                dist_data = ks_distributions[selected_feature]
                q1_values = dist_data.get('q1', [])
                q4_values = dist_data.get('q4', [])

                if q1_values and q4_values:
                    # Create side-by-side histograms
                    fig = go.Figure()

                    fig.add_trace(go.Histogram(
                        x=q1_values,
                        name='Q1 (Losers)',
                        marker_color='rgba(239, 83, 80, 0.6)',
                        nbinsx=30
                    ))

                    fig.add_trace(go.Histogram(
                        x=q4_values,
                        name='Q4 (Winners)',
                        marker_color='rgba(38, 166, 154, 0.6)',
                        nbinsx=30
                    ))

                    # Add median lines
                    fig.add_vline(
                        x=dist_data.get('q1_median', 0),
                        line_dash="dash",
                        line_color="red",
                        annotation_text=f"Q1 Median: {dist_data.get('q1_median', 0):.2f}"
                    )
                    fig.add_vline(
                        x=dist_data.get('q4_median', 0),
                        line_dash="dash",
                        line_color="green",
                        annotation_text=f"Q4 Median: {dist_data.get('q4_median', 0):.2f}"
                    )

                    fig.update_layout(
                        title=f"KS Distribution: {selected_feature}",
                        barmode='overlay',
                        xaxis_title=selected_feature,
                        yaxis_title='Count',
                        template='plotly_white',
                        height=400
                    )

                    st.plotly_chart(fig, use_container_width=True)

                    # Show separation metric
                    q1_med = dist_data.get('q1_median', 0)
                    q4_med = dist_data.get('q4_median', 0)
                    separation = abs(q4_med - q1_med)
                    st.metric("Median Separation", f"{separation:.3f}")
        else:
            st.info("KS distribution data not available. Run EDA workflow to generate.")

    # Tab 3: Decile Plots (Enhanced with Box Plots)
    with tab3:
        st.markdown("### Decile Monotonicity Analysis")
        st.markdown("**Box plots** show return distribution per decile - revealing variance hidden by mean charts")

        # Check for enhanced box plot data first
        decile_box_data = eda_data.get('decile_box_data', {})
        decile_stats = eda_data.get('decile_stats', {})

        if decile_box_data:
            # Feature selector for box plots
            features = list(decile_box_data.keys())
            selected_feature = st.selectbox("Select Feature:", features, key='decile_box_feature')

            if selected_feature and selected_feature in decile_box_data:
                box_arrays = decile_box_data[selected_feature]

                # Create box plot using RAW DATA
                fig = go.Figure()

                for decile_name in sorted(box_arrays.keys(), key=lambda x: int(x[1:])):
                    returns = box_arrays[decile_name]
                    decile_num = int(decile_name[1:])

                    fig.add_trace(go.Box(
                        y=returns,
                        name=decile_name,
                        boxpoints='outliers',
                        jitter=0.3,
                        pointpos=-1.8,
                        marker=dict(
                            color='#2ca02c' if decile_num == 10 else '#1f77b4',
                            size=2,
                            opacity=0.5
                        ),
                        line=dict(color='black', width=1),
                        boxmean=True
                    ))

                fig.add_hline(y=0, line_dash="dash", line_color="red", line_width=2)

                fig.update_layout(
                    title=f"<b>{selected_feature}</b>: Return Distribution by Decile",
                    xaxis_title="Decile (1=Lowest, 10=Highest)",
                    yaxis_title="Return %",
                    template='plotly_white',
                    height=600,
                    showlegend=False,
                    yaxis=dict(
                        range=[-30, 100],
                        zeroline=True,
                        zerolinewidth=2,
                        zerolinecolor='red'
                    )
                )

                st.plotly_chart(fig, use_container_width=True)

                # Summary metrics
                d1_returns = box_arrays.get('D1', [])
                d10_returns = box_arrays.get('D10', [])

                if d1_returns and d10_returns:
                    import numpy as np
                    col1, col2, col3, col4 = st.columns(4)
                    with col1:
                        st.metric("D1 Median", f"{np.median(d1_returns):.2f}%")
                    with col2:
                        st.metric("D10 Median", f"{np.median(d10_returns):.2f}%")
                    with col3:
                        spread = np.median(d10_returns) - np.median(d1_returns)
                        st.metric("Spread (Median)", f"{spread:+.2f}%")
                    with col4:
                        st.metric("D10 Max", f"{np.max(d10_returns):.1f}%",
                                 help="Outliers (home runs) in top decile")

                    # Variance insight
                    st.info(
                        f"D10 Std: {np.std(d10_returns):.1f}% | "
                        f"D1 Std: {np.std(d1_returns):.1f}% - "
                        f"High variance in D10 suggests edge comes from **outliers (home runs)**, not consistency"
                    )

        elif decile_stats:
            # Fallback to legacy bar chart
            features = list(decile_stats.keys())
            selected_feature = st.selectbox("Select Feature:", features, key='decile_feature')

            if selected_feature and selected_feature in decile_stats:
                stats = decile_stats[selected_feature]
                decile_returns = stats.get('decile_returns', [])

                if decile_returns:
                    deciles = [f'D{i}' for i in range(1, len(decile_returns) + 1)]
                    colors = ['rgba(239, 83, 80, 0.7)' if r < 0 else 'rgba(38, 166, 154, 0.7)' for r in decile_returns]

                    fig = go.Figure(data=[
                        go.Bar(x=deciles, y=decile_returns, marker_color=colors,
                               text=[f'{r:.2f}%' for r in decile_returns], textposition='outside')
                    ])
                    fig.update_layout(
                        title=f"Decile Returns: {selected_feature} (Mean only - upgrade EDA for box plots)",
                        xaxis_title='Feature Decile', yaxis_title='Mean Return (%)',
                        template='plotly_white', height=400
                    )
                    st.plotly_chart(fig, use_container_width=True)
        else:
            st.info("Decile data not available. Run EDA workflow to generate.")

    # Tab 4: Industry Analysis (Box Plots)
    with tab4:
        st.markdown("### Industry Performance Analysis")
        st.markdown("Return distribution by industry - categorical analysis (not monotonicity)")

        industry_box_data = eda_data.get('industry_box_data', [])
        if industry_box_data:
            # Create industry box plot using RAW DATA
            fig = go.Figure()

            for ind in industry_box_data[:15]:  # Top 15 industries
                returns = ind['returns']
                fig.add_trace(go.Box(
                    y=returns,
                    name=ind['industry'][:20],  # Truncate long names
                    boxpoints='outliers',
                    marker=dict(
                        color='#1f77b4',
                        size=2,
                        opacity=0.5
                    ),
                    line=dict(color='black', width=1),
                    boxmean=True
                ))

            fig.add_hline(y=0, line_dash="dash", line_color="gray", opacity=0.5)

            fig.update_layout(
                title="Return Distribution by Industry (Top 15 by Frequency)",
                xaxis_title='Industry',
                yaxis_title='Return (%)',
                template='plotly_white',
                height=500,
                showlegend=False,
                xaxis_tickangle=-45
            )

            st.plotly_chart(fig, use_container_width=True)

            # Summary table
            st.markdown("#### Industry Statistics")
            import numpy as np
            summary_data = []
            for ind in industry_box_data:
                returns = ind['returns']
                summary_data.append({
                    'Industry': ind['industry'],
                    'Trades': ind['count'],
                    'Median %': np.median(returns),
                    'Mean %': np.mean(returns),
                    'Win Rate %': (np.array(returns) > 0).mean() * 100,
                    '>50% Return %': (np.array(returns) > 50).mean() * 100,
                    'Std Dev': np.std(returns)
                })

            ind_df = pd.DataFrame(summary_data)
            st.dataframe(
                ind_df.style.format({
                    'Median %': '{:.2f}',
                    'Mean %': '{:.2f}',
                    'Win Rate %': '{:.1f}',
                    '>50% Return %': '{:.1f}',
                    'Std Dev': '{:.1f}'
                }),
                use_container_width=True,
                hide_index=True
            )
        else:
            st.info("Industry performance data not available. Run EDA workflow to generate.")

    # Tab 5: Super-Performer Analysis
    with tab5:
        st.markdown("### Super-Performer Analysis")
        st.markdown("**The Home-Run Hunter**: What are the odds of catching a 100%+ winner?")

        super_perf = eda_data.get('super_performer_analysis', {})
        if super_perf:
            # Show summary metrics for key deciles
            col1, col2, col3 = st.columns(3)

            decile_configs = [
                ('decile_1', 'D1 (Lowest RS)', col1),
                ('decile_5', 'D5 (Middle RS)', col2),
                ('decile_10', 'D10 (Highest RS)', col3)
            ]

            for decile_key, title, col in decile_configs:
                if decile_key not in super_perf:
                    continue

                data = super_perf[decile_key]
                with col:
                    st.markdown(f"#### {title}")
                    st.metric("Home Runs (>100%)", f"{data['n_home_runs']} ({data['pct_home_runs']:.1f}%)")
                    st.metric("Super-Performers (>50%)", f"{data['n_super_performers']} ({data['pct_super_performers']:.1f}%)")
                    st.metric("Median Return", f"{data['median_return']:.1f}%")

            st.markdown("---")

            # Histogram comparison - ALL 10 DECILES
            st.markdown("#### Return Distribution by RS Decile (All 10)")

            fig = go.Figure()

            # Color gradient from red (D1) to green (D10)
            import plotly.express as px
            colors = px.colors.sample_colorscale("RdYlGn", [i/9 for i in range(10)])

            for decile_num in range(1, 11):
                decile_key = f'decile_{decile_num}'
                if decile_key not in super_perf:
                    continue

                data = super_perf[decile_key]
                fig.add_trace(go.Bar(
                    name=f'D{decile_num}',
                    x=data['return_bins'],
                    y=data['counts'],
                    marker_color=colors[decile_num - 1],
                    text=data['counts'],
                    textposition='outside',
                    hovertemplate=(
                        f"<b>Decile {decile_num}</b><br>"
                        f"Bin: %{{x}}<br>"
                        f"Count: %{{y}}<br>"
                        f"Home Runs: {data['n_home_runs']} ({data['pct_home_runs']:.1f}%)<extra></extra>"
                    )
                ))

            fig.update_layout(
                title="Trade Count by Return Bucket (Log Scale)",
                xaxis_title='Return Range',
                yaxis_title='Number of Trades',
                yaxis_type='log',
                barmode='group',
                template='plotly_white',
                height=500,
                legend=dict(
                    orientation='v',
                    yanchor='top',
                    y=1,
                    xanchor='right',
                    x=1.15
                )
            )

            st.plotly_chart(fig, use_container_width=True)

            # Key insight
            if 'decile_10' in super_perf and 'decile_1' in super_perf:
                d10_hr = super_perf['decile_10']['pct_home_runs']
                d1_hr = super_perf['decile_1']['pct_home_runs']
                if d10_hr > 0 and d1_hr == 0:
                    st.success(
                        f"D10 has {d10_hr:.1f}% home runs vs D1's {d1_hr:.1f}%. "
                        f"**Relative Strength is the gateway to Super-Performers.**"
                    )
                elif d10_hr > d1_hr:
                    st.info(f"D10 has {d10_hr:.1f}% home runs vs D1's {d1_hr:.1f}%")
        else:
            st.info("Super-performer analysis not available. Run EDA workflow to generate.")

    # Tab 6: IC Stability
    with tab6:
        st.markdown("### IC Temporal Stability")
        st.markdown("Information Coefficient consistency across years")

        ic_time_series = eda_data.get('ic_time_series', {})
        if ic_time_series:
            # Feature selector
            features = list(ic_time_series.keys())
            selected_features = st.multiselect(
                "Select Features (max 5):",
                features,
                default=features[:3] if len(features) >= 3 else features,
                max_selections=5
            )

            if selected_features:
                fig = go.Figure()

                for feature in selected_features:
                    ic_data = ic_time_series[feature]
                    yearly_ics = ic_data.get('yearly_ics', {})

                    if yearly_ics:
                        years = sorted(yearly_ics.keys())
                        values = [yearly_ics[y] for y in years]

                        fig.add_trace(go.Scatter(
                            x=years,
                            y=values,
                            name=feature,
                            mode='lines+markers'
                        ))

                fig.add_hline(y=0, line_dash="dash", line_color="gray")

                fig.update_layout(
                    title="IC Time Series by Year",
                    xaxis_title='Year',
                    yaxis_title='Information Coefficient',
                    template='plotly_white',
                    height=400
                )

                st.plotly_chart(fig, use_container_width=True)

                # Show regime-conditional features
                regime_features = [f for f in ic_time_series if ic_time_series[f].get('is_regime_conditional', False)]
                if regime_features:
                    st.warning(f"Regime-Conditional Features (high IC variance): {', '.join(regime_features[:10])}")
        else:
            st.info("IC time series data not available. Run EDA workflow to generate.")

    # Categorical encoding section
    st.markdown("---")
    st.markdown("### Categorical Feature Encoding")
    categorical_encoding = eda_data.get('categorical_encoding', {})
    if categorical_encoding:
        for cat_col, stats in categorical_encoding.items():
            st.markdown(f"**{cat_col}** → `{stats.get('encoded_col', '')}` "
                       f"({stats.get('n_categories', 0)} categories, global mean: {stats.get('global_mean', 0):.2f}%)")
    else:
        st.info("No categorical features encoded")

    # Transform summary
    st.markdown("---")
    with st.expander("📋 Transform Summary", expanded=False):
        transform_summary = eda_data.get('transform_summary', {})
        log_features = transform_summary.get('log', [])
        winsorized_features = transform_summary.get('winsorized', [])

        col1, col2 = st.columns(2)
        with col1:
            st.markdown(f"**Log-Transformed ({len(log_features)}):**")
            if log_features:
                st.text('\n'.join(log_features[:20]))
                if len(log_features) > 20:
                    st.text(f"... and {len(log_features) - 20} more")
        with col2:
            st.markdown(f"**Winsorized ({len(winsorized_features)}):**")
            if winsorized_features:
                st.text('\n'.join(winsorized_features[:20]))
                if len(winsorized_features) > 20:
                    st.text(f"... and {len(winsorized_features) - 20} more")
